# Project Diary

**I have decided that as I already have the fixed broadband data stored in a MongoDb collection that it would be a good idea to clean and import the census data into the same MongoDb instance as its own collection.  I have looked at the census spreadsheets and have decided to form a question using the employment data and combine this with the fixed broadband to form a second question.**

In [1]:
#import libraries
import pandas as pd
import numpy as np
import pymongo
import re
import chardet
import glob 
import folium

In [2]:
#runs the TMA2 Q1 notebook containing the fixed broadband mongodb collection
%run K4782084_q1_TMA02-Copy1.ipynb

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
2023J_TMA02_data/Ofcom_fixed/201909_fixed_laua_coverage_r01.csv
laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,% of premises unable to receive 30Mbit/s,% of premises below the USO,% of premises with NGA,% of premises able to receive decent broadband from FWA,% of premises able to receive SFBB from FWA,Number of premises with SFBB availability,Number of premises with UFBB availability,Number of premises with Full Fibre availability,Number of premises unable to receive 2Mbit/s,Number of premises unable to receive 5Mbit/s,Number of premises unable to receive 10Mbit/s,Number of premises unable to receive 30Mbit/s,Number of premises below the USO,Number of premises with NGA,Number of premises able to receive decent broadband from FWA,Number of premises able to receive SFBB from FWA,Number of premises with 30<300Mbit/s download speed,Number of premises with >=300Mbit/s download speed,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
S12000033,ABERDEEN CITY,125441,125311,73.3,20.1,13.1,0,0.2,0.7,6.5,0.2,96.8,0,0,117152,25163,16410,49,219,884,8159,189,121476,0,0,91989,25163,49,170,665,7275,73.3,20.1,0,0.1,0.5,5.8
S12000034,ABERDEENSHIRE,125085,124305,78.5,2.8,2.7,2.5,5.9,9.9,18.1,3.6,93.6,0,0,101652,3472,3332,3163,7339,12332,22653,4519,117051,0,0,98180,3472,3163,4176,4993,10321,78.5,2.8,2.5,3.3,4,8.3
E07000223,ADUR,29770,29760,16.3,82.4,0.6,0,0.1,0.1,1.3,0,99.1,0,0,29383,24543,193,0,16,44,377,12,29514,0,0,4840,24543,0,16,28,333,16.3,82.4,0,0.1,0.1,1.1
E07000026,ALLERDALE,51385,51284,89.8,1.7,1.7,1.2,2.6,3.6,8.3,1.2,98.3,2.3,2.2,47003,866,866,619,1323,1873,4281,592,50507,1164,1114,46137,866,619,704,550,2408,89.8,1.7,1.2,1.4,1.1,4.7

2023J_TMA02_data/Ofcom_fixed/202009_fixed_laua_coverage_r01.csv
laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,% of premises unable to receive 30Mbit/s,% of premises below the USO,% of premises with NGA,% of premises able to receive decent broadband from FWA,Number of premises with SFBB availability,Number of premises with UFBB (100Mbit/s) availability,Number of premises with UFBB availability,Number of premises with Full Fibre availability,Number of premises with Gigabit availability,Number of premises unable to receive 2Mbit/s,Number of premises unable to receive 5Mbit/s,Number of premises unable to receive 10Mbit/s,Number of premises unable to receive 30Mbit/s,Number of premises below the USO,Number of premises with NGA,Number of premises able to receive decent broadband from FWA,Number of premises with 30<300Mbit/s download speed,Number of premises with >=300Mbit/s download speed,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
S12000033,ABERDEEN CITY,126176,125948,94.6,49.0,41.6,34.9,34.9,0.0,0.2,0.7,5.2,0.2,97.0,0.0,119358,61798,52461,44051,44051,55,208,881,6590,300,122434,0,66897,52461,55,153,673,5709,53.0,41.6,0.0,0.1,0.5,4.5
S12000034,ABERDEENSHIRE,126065,125176,82.9,7.2,7.0,6.9,6.9,2.6,5.6,9.1,16.4,3.6,94.7,0.0,104472,9118,8872,8732,8732,3234,7099,11516,20704,4538,119331,0,95600,8872,3234,3865,4417,9188,75.8,7.0,2.6,3.1,3.5,7.3
E07000223,ADUR,29779,29755,98.8,85.8,85.6,0.6,0.6,0.0,0.0,0.1,1.1,0.1,99.5,0.0,29427,25562,25482,189,189,0,10,34,328,33,29616,0,3945,25482,0,10,24,294,13.2,85.6,0.0,0.0,0.1,1.0
E07000026,ALLERDALE,51647,51483,92.3,2.8,2.8,2.8,2.8,1.2,2.3,3.3,7.3,1.2,98.6,2.2,47693,1466,1466,1466,1466,627,1173,1705,3790,634,50931,1160,46227,1466,627,546,532,2085,89.5,2.8,1.2,1.1,1.0,4.0

2023J_TMA02_data/Ofcom_fixed/202305_fixed_laua_coverage_r02.csv
laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,% of premises unable to receive 30Mbit/s,% of premises below the USO,% of premises with NGA,% of premises able to receive decent broadband from FWA,Number of premises with SFBB availability,Number of premises with UFBB (100Mbit/s) availability,Number of premises with UFBB availability,Number of premises with Full Fibre availability,Number of premises with Gigabit availability,Number of premises unable to receive 2Mbit/s,Number of premises unable to receive 5Mbit/s,Number of premises unable to receive 10Mbit/s,Number of premises unable to receive 30Mbit/s,Number of premises below the USO,Number of premises with NGA,Number of premises able to receive decent broadband from FWA,Number of premises with 30<300Mbit/s download speed,Number of premises with >=300Mbit/s download speed,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
S12000033,ABERDEEN CITY,129315,129197,97.2,84.8,83.9,83,83,0,0.2,0.3,2.8,0,98,0,125636,109650,108514,107315,107315,58,209,431,3561,40,126770,0,17122,108514,58,151,222,3130,13.2,83.9,0,0.1,0.2,2.4
S12000034,ABERDEENSHIRE,128408,128070,85.9,25.5,25.5,25.4,25.4,1.7,4.2,7.6,13.8,2.4,95.4,0,110296,32794,32703,32622,32622,2214,5407,9703,17774,3047,122495,0,77593,32703,2214,3193,4296,8071,60.4,25.5,1.7,2.5,3.3,6.3
E07000223,ADUR,29985,29953,99.1,92.8,92.8,65.4,92.8,0,0,0.1,0.8,0,99.6,0,29727,27826,27826,19606,27826,0,9,40,226,5,29864,0,1901,27826,0,9,31,186,6.3,92.8,0,0,0.1,0.6
E07000026,ALLERDALE,52482,52364,93.1,6,6,6,6,1.2,2,2.8,6.6,0.6,98.7,3.4,48885,3127,3127,3127,3127,617,1057,1479,3479,294,51819,1785,45758,3127,617,440,422,2000,87.2,6,1.2,0.8,0.8,3.8

2023J_TMA02_data/Ofcom_fixed/202109_fixed_laua_coverage_r01.csv
laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,% of premises unable to receive 30Mbit/s,% of premises below the USO,% of premises with NGA,% of premises able to receive decent broadband from FWA,Number of premises with SFBB availability,Number of premises with UFBB (100Mbit/s) availability,Number of premises with UFBB availability,Number of premises with Full Fibre availability,Number of premises with Gigabit availability,Number of premises unable to receive 2Mbit/s,Number of premises unable to receive 5Mbit/s,Number of premises unable to receive 10Mbit/s,Number of premises unable to receive 30Mbit/s,Number of premises below the USO,Number of premises with NGA,Number of premises able to receive decent broadband from FWA,Number of premises with 30<300Mbit/s download speed,Number of premises with >=300Mbit/s download speed,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
S12000033,ABERDEEN CITY,127714,126771,94.7,66.6,62.1,58.4,58.4,0.1,0.2,0.5,4.6,0.1,96.4,0.0,120938,85048,79372,74618,74618,67,211,628,5833,93,123177,0,41566,79372,67,144,417,5205,32.5,62.1,0.1,0.1,0.3,4.1
S12000034,ABERDEENSHIRE,126481,125378,82.8,13.8,13.7,13.7,13.7,2.5,5.7,9.2,16.3,3.7,94.4,0.0,104761,17459,17366,17269,17269,3202,7186,11631,20617,4727,119421,0,87395,17366,3202,3984,4445,8986,69.1,13.7,2.5,3.1,3.5,7.1
E07000223,ADUR,29884,29793,98.6,85.9,85.6,1.8,1.8,0.0,0.0,0.1,1.1,0.0,99.3,0.0,29476,25660,25581,538,538,4,13,36,317,8,29670,0,3895,25581,4,9,23,281,13.0,85.6,0.0,0.0,0.1,0.9
E07000026,ALLERDALE,51933,51622,92.3,3.4,3.4,3.4,3.4,1.1,2.1,3.1,7.1,1.0,98.4,0.0,47922,1750,1750,1750,1750,595,1098,1612,3700,518,51077,0,46172,1750,595,503,514,2088,88.9,3.4,1.1,1.0,1.0,4.0

2023J_TMA02_data/Ofcom_fixed/202209_fixed_laua_coverage_r02.csv
laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,% of premises unable to receive 30Mbit/s,% of premises below the USO,% of premises with NGA,% of premises able to receive decent broadband from FWA,Number of premises with SFBB availability,Number of premises with UFBB (100Mbit/s) availability,Number of premises with UFBB availability,Number of premises with Full Fibre availability,Number of premises with Gigabit availability,Number of premises unable to receive 2Mbit/s,Number of premises unable to receive 5Mbit/s,Number of premises unable to receive 10Mbit/s,Number of premises unable to receive 30Mbit/s,Number of premises below the USO,Number of premises with NGA,Number of premises able to receive decent broadband from FWA,Number of premises with 30<300Mbit/s download speed,Number of premises with >=300Mbit/s download speed,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
S12000033,ABERDEEN CITY,128708,128294,95.8,79.1,77.1,74.4,74.4,0.0,0.1,0.4,3.9,0.0,97.1,0.0,123335,101776,99197,95719,95719,59,178,548,4959,55,125036,0,24138,99197,59,119,370,4411,18.8,77.1,0.0,0.1,0.3,3.4
S12000034,ABERDEENSHIRE,127941,127265,84.2,20.6,20.5,20.5,20.5,1.8,4.5,8.2,15.3,2.6,94.8,0.0,107742,26341,26251,26171,26171,2330,5780,10440,19523,3335,121312,0,81491,26251,2330,3450,4660,9083,63.7,20.5,1.8,2.7,3.6,7.1
E07000223,ADUR,29971,29920,99.1,91.0,91.0,54.5,90.1,0.0,0.0,0.2,0.8,0.0,99.5,0.0,29687,27264,27264,16333,27009,2,8,47,233,7,29826,0,2423,27264,2,6,39,186,8.1,91.0,0.0,0.0,0.1,0.6
E07000026,ALLERDALE,52309,52133,92.7,5.4,5.4,5.4,5.4,1.2,2.1,2.9,6.9,0.6,98.6,3.4,48499,2811,2811,2811,2811,630,1086,1541,3634,327,51583,1788,45688,2811,630,456,455,2093,87.3,5.4,1.2,0.9,0.9,4.0

E07000239,WYRE FOREST,48100,48061,49.3,46.7,0.9,0.3,0.6,1.4,3.9,0.5,99.4,2.9,0.4,46203,22479,420,140,291,662,1858,264,47829,1412,172,23724,22479,140,151,371,1196,49.3,46.7,0.3,0.3,0.8,2.5
E06000014,YORK,98735,98548,23,70.8,43.6,0,0.3,0.6,6,0.2,95.6,7,3.9,92626,69871,43077,36,261,629,5922,191,94419,6956,3811,22755,69871,36,225,368,5293,23,70.8,0,0.2,0.4,5.4

E07000239,WYRE FOREST,48237,48173,96.8,47.9,47.8,2.0,47.8,0.2,0.5,0.8,3.1,0.4,99.5,3.5,46680,23125,23035,961,23034,84,218,389,1493,183,48001,1675,23645,23035,84,134,171,1104,49.0,47.8,0.2,0.3,0.4,2.3
E06000014,YORK,95949,95674,94.1,75.5,71.9,54.8,54.8,0.0,0.2,0.8,5.6,0.3,96.0,3.7,90313,72415,68952,52549,52549,39,209,774,5361,296,92085,3522,21361,68952,39,170,565,4587,22.3,71.9,0.0,0.2,0.6,4.8

E07000239,WYRE FOREST,49121,49027,97.8,63.8,63.8,25.7,63.8,0.1,0.2,0.4,2,0.1,99.6,3.4,48048,31340,31340,12612,31340,45,115,202,979,52,48916,1669,16708,31340,45,70,87,777,34,63.8,0.1,0.1,0.2,1.6
E06000014,YORK,96725,96582,95.4,80.6,78.4,65.9,76.3,0,0.1,0.5,4.4,0,96.9,21.8,92312,78000,75825,63736,73780,43,142,465,4270,16,93763,21109,16487,75825,43,99,323,3805,17,78.4,0,0.1,0.3,3.9

E07000239,WYRE FOREST,48472,48204,96.7,48.5,48.1,2.6,48.1,0.1,0.3,0.7,2.8,0.2,99.1,3.4,46859,23514,23324,1276,23324,45,141,323,1345,94,48058,1662,23535,23324,45,96,182,1022,48.6,48.1,0.1,0.2,0.4,2.1
E06000014,YORK,96147,95638,94.2,77.5,74.5,60.4,72.0,0.0,0.2,0.7,5.2,0.0,96.1,7.1,90609,74466,71630,58026,69189,41,182,668,5029,32,92376,6860,18979,71630,41,141,486,4361,19.7,74.5,0.0,0.1,0.5,4.5

E07000239,WYRE FOREST,48894,48679,97.3,55.7,55.7,10.3,55.4,0.1,0.3,0.5,2.3,0.1,99.3,3.4,47557,27255,27255,5020,27064,49,136,250,1122,69,48549,1670,20302,27255,49,87,114,872,41.5,55.7,0.1,0.2,0.2,1.8
E06000014,YORK,96526,96317,94.7,75.8,72.6,52.3,70.0,0.0,0.2,0.7,5.0,0.0,96.6,3.8,91448,73123,70059,50466,67521,42,189,694,4869,23,93230,3707,21389,70059,42,147,505,4175,22.2,72.6,0.0,0.2,0.5,4.3

2023J_TMA02_data/Ofcom_fixed/201909_fixed_laua_coverage_r01.csv : 201909_fixed_laua_coverage_r01
2023J_TMA02_data/Ofcom_fixed/202009_fixed_laua_coverage_r01.csv : 202009_fixed_laua_coverage_r01
2023J_TMA02_data/Ofcom_fixed/202305_fixed_laua_coverage_r02.csv : 202305_fixed_laua_coverage_r02
2023J_TMA02_data/Ofcom_fixed/202109_fixed_laua_coverage_r01.csv : 202109_fixed_laua_coverage_r01
2023J_TMA02_data/Ofcom_fixed/202209_fixed_laua_coverage_r02.csv : 202209_fixed_laua_coverage_r02

 df_2019

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,125441,125311,73.3,20.1,13.1,0.0,0.2,0.7,...,49,170,665,7275,73.3,20.1,0.0,0.1,0.5,5.8
1,S12000034,ABERDEENSHIRE,125085,124305,78.5,2.8,2.7,2.5,5.9,9.9,...,3163,4176,4993,10321,78.5,2.8,2.5,3.3,4.0,8.3
2,E07000223,ADUR,29770,29760,16.3,82.4,0.6,0.0,0.1,0.1,...,0,16,28,333,16.3,82.4,0.0,0.1,0.1,1.1
3,E07000026,ALLERDALE,51385,51284,89.8,1.7,1.7,1.2,2.6,3.6,...,619,704,550,2408,89.8,1.7,1.2,1.4,1.1,4.7
4,E07000032,AMBER VALLEY,60674,60596,67.4,25.3,22.1,0.1,0.9,2.1,...,89,460,705,3110,67.4,25.3,0.1,0.8,1.2,5.1

laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premises able to receive decent broadband from FWA         0
% of premises able to receive SFBB from FWA                     0
Number of premises with SFBB availability                       0
Number of premises with UFBB availability                       0
Number of premises with Full Fibre availability                 0
Number of premises unable to receive 2Mbit/s                    0
Number of premises unable to receive 5Mbit/s                    0
Number of premises unable to receive 10Mbit/s                   0
Number of premises unable to receive 30Mbit/s                   0
Number of premises below the USO                                0
Number of premises with NGA                                     0
Number of premises able to receive decent broadband from FWA    0
Number of premises able to receive SFBB from FWA                0
Number of premises with 30<300Mbit/s download speed             0
Number of premises with >=300Mbit/s download speed              0
Number of premises with 0<2Mbit/s download speed                0
Number of premises with 2<5Mbit/s download speed                0
Number of premises with 5<10Mbit/s download speed               0
Number of premises with 10<30Mbit/s download speed              0
% of premises with 30<300Mbit/s download speed                  0
% of premises with >=300Mbit/s download speed                   0
% of premises with 0<2Mbit/s download speed                     0
% of premises with 2<5Mbit/s download speed                     0
% of premises with 5<10Mbit/s download speed                    0
% of premises with 10<30Mbit/s download speed                   0
dtype: int64

 df_2020

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,126176,125948,94.6,49.0,41.6,34.9,34.9,0.0,...,55,153,673,5709,53.0,41.6,0.0,0.1,0.5,4.5
1,S12000034,ABERDEENSHIRE,126065,125176,82.9,7.2,7.0,6.9,6.9,2.6,...,3234,3865,4417,9188,75.8,7.0,2.6,3.1,3.5,7.3
2,E07000223,ADUR,29779,29755,98.8,85.8,85.6,0.6,0.6,0.0,...,0,10,24,294,13.2,85.6,0.0,0.0,0.1,1.0
3,E07000026,ALLERDALE,51647,51483,92.3,2.8,2.8,2.8,2.8,1.2,...,627,546,532,2085,89.5,2.8,1.2,1.1,1.0,4.0
4,E07000032,AMBER VALLEY,61134,60972,94.7,30.2,26.7,23.6,23.6,0.1,...,63,217,293,2524,68.0,26.7,0.1,0.4,0.5,4.1

laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB (100Mbit/s) availability (% premises)                      0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
Gigabit availability (% premises)                               0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premises able to receive decent broadband from FWA         0
Number of premises with SFBB availability                       0
Number of premises with UFBB (100Mbit/s) availability           0
Number of premises with UFBB availability                       0
Number of premises with Full Fibre availability                 0
Number of premises with Gigabit availability                    0
Number of premises unable to receive 2Mbit/s                    0
Number of premises unable to receive 5Mbit/s                    0
Number of premises unable to receive 10Mbit/s                   0
Number of premises unable to receive 30Mbit/s                   0
Number of premises below the USO                                0
Number of premises with NGA                                     0
Number of premises able to receive decent broadband from FWA    0
Number of premises with 30<300Mbit/s download speed             0
Number of premises with >=300Mbit/s download speed              0
Number of premises with 0<2Mbit/s download speed                0
Number of premises with 2<5Mbit/s download speed                0
Number of premises with 5<10Mbit/s download speed               0
Number of premises with 10<30Mbit/s download speed              0
% of premises with 30<300Mbit/s download speed                  0
% of premises with >=300Mbit/s download speed                   0
% of premises with 0<2Mbit/s download speed                     0
% of premises with 2<5Mbit/s download speed                     0
% of premises with 5<10Mbit/s download speed                    0
% of premises with 10<30Mbit/s download speed                   0
dtype: int64

 df_2023

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,129315,129197,97.2,84.8,83.9,83.0,83.0,0.0,...,58,151,222,3130,13.2,83.9,0.0,0.1,0.2,2.4
1,S12000034,ABERDEENSHIRE,128408,128070,85.9,25.5,25.5,25.4,25.4,1.7,...,2214,3193,4296,8071,60.4,25.5,1.7,2.5,3.3,6.3
2,E07000223,ADUR,29985,29953,99.1,92.8,92.8,65.4,92.8,0.0,...,0,9,31,186,6.3,92.8,0.0,0.0,0.1,0.6
3,E07000026,ALLERDALE,52482,52364,93.1,6.0,6.0,6.0,6.0,1.2,...,617,440,422,2000,87.2,6.0,1.2,0.8,0.8,3.8
4,E07000032,AMBER VALLEY,62512,62430,97.2,62.4,60.6,59.0,59.1,0.1,...,42,115,88,1415,36.6,60.6,0.1,0.2,0.1,2.3

laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB (100Mbit/s) availability (% premises)                      0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
Gigabit availability (% premises)                               0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premises able to receive decent broadband from FWA         0
Number of premises with SFBB availability                       0
Number of premises with UFBB (100Mbit/s) availability           0
Number of premises with UFBB availability                       0
Number of premises with Full Fibre availability                 0
Number of premises with Gigabit availability                    0
Number of premises unable to receive 2Mbit/s                    0
Number of premises unable to receive 5Mbit/s                    0
Number of premises unable to receive 10Mbit/s                   0
Number of premises unable to receive 30Mbit/s                   0
Number of premises below the USO                                0
Number of premises with NGA                                     0
Number of premises able to receive decent broadband from FWA    0
Number of premises with 30<300Mbit/s download speed             0
Number of premises with >=300Mbit/s download speed              0
Number of premises with 0<2Mbit/s download speed                0
Number of premises with 2<5Mbit/s download speed                0
Number of premises with 5<10Mbit/s download speed               0
Number of premises with 10<30Mbit/s download speed              0
% of premises with 30<300Mbit/s download speed                  0
% of premises with >=300Mbit/s download speed                   0
% of premises with 0<2Mbit/s download speed                     0
% of premises with 2<5Mbit/s download speed                     0
% of premises with 5<10Mbit/s download speed                    0
% of premises with 10<30Mbit/s download speed                   0
dtype: int64

 df_2021

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,127714,126771,94.7,66.6,62.1,58.4,58.4,0.1,...,67,144,417,5205,32.5,62.1,0.1,0.1,0.3,4.1
1,S12000034,ABERDEENSHIRE,126481,125378,82.8,13.8,13.7,13.7,13.7,2.5,...,3202,3984,4445,8986,69.1,13.7,2.5,3.1,3.5,7.1
2,E07000223,ADUR,29884,29793,98.6,85.9,85.6,1.8,1.8,0.0,...,4,9,23,281,13.0,85.6,0.0,0.0,0.1,0.9
3,E07000026,ALLERDALE,51933,51622,92.3,3.4,3.4,3.4,3.4,1.1,...,595,503,514,2088,88.9,3.4,1.1,1.0,1.0,4.0
4,E07000032,AMBER VALLEY,61555,61161,95.1,31.4,27.9,25.2,25.2,0.1,...,61,129,189,2266,67.2,27.9,0.1,0.2,0.3,3.7

laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB (100Mbit/s) availability (% premises)                      0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
Gigabit availability (% premises)                               0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premises able to receive decent broadband from FWA         0
Number of premises with SFBB availability                       0
Number of premises with UFBB (100Mbit/s) availability           0
Number of premises with UFBB availability                       0
Number of premises with Full Fibre availability                 0
Number of premises with Gigabit availability                    0
Number of premises unable to receive 2Mbit/s                    0
Number of premises unable to receive 5Mbit/s                    0
Number of premises unable to receive 10Mbit/s                   0
Number of premises unable to receive 30Mbit/s                   0
Number of premises below the USO                                0
Number of premises with NGA                                     0
Number of premises able to receive decent broadband from FWA    0
Number of premises with 30<300Mbit/s download speed             0
Number of premises with >=300Mbit/s download speed              0
Number of premises with 0<2Mbit/s download speed                0
Number of premises with 2<5Mbit/s download speed                0
Number of premises with 5<10Mbit/s download speed               0
Number of premises with 10<30Mbit/s download speed              0
% of premises with 30<300Mbit/s download speed                  0
% of premises with >=300Mbit/s download speed                   0
% of premises with 0<2Mbit/s download speed                     0
% of premises with 2<5Mbit/s download speed                     0
% of premises with 5<10Mbit/s download speed                    0
% of premises with 10<30Mbit/s download speed                   0
dtype: int64

 df_2022

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,128708,128294,95.8,79.1,77.1,74.4,74.4,0.0,...,59,119,370,4411,18.8,77.1,0.0,0.1,0.3,3.4
1,S12000034,ABERDEENSHIRE,127941,127265,84.2,20.6,20.5,20.5,20.5,1.8,...,2330,3450,4660,9083,63.7,20.5,1.8,2.7,3.6,7.1
2,E07000223,ADUR,29971,29920,99.1,91.0,91.0,54.5,90.1,0.0,...,2,6,39,186,8.1,91.0,0.0,0.0,0.1,0.6
3,E07000026,ALLERDALE,52309,52133,92.7,5.4,5.4,5.4,5.4,1.2,...,630,456,455,2093,87.3,5.4,1.2,0.9,0.9,4.0
4,E07000032,AMBER VALLEY,62170,61902,96.1,49.4,46.2,43.6,43.7,0.1,...,58,103,126,1855,49.9,46.2,0.1,0.2,0.2,3.0

laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB (100Mbit/s) availability (% premises)                      0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
Gigabit availability (% premises)                               0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premises able to receive decent broadband from FWA         0
Number of premises with SFBB availability                       0
Number of premises with UFBB (100Mbit/s) availability           0
Number of premises with UFBB availability                       0
Number of premises with Full Fibre availability                 0
Number of premises with Gigabit availability                    0
Number of premises unable to receive 2Mbit/s                    0
Number of premises unable to receive 5Mbit/s                    0
Number of premises unable to receive 10Mbit/s                   0
Number of premises unable to receive 30Mbit/s                   0
Number of premises below the USO                                0
Number of premises with NGA                                     0
Number of premises able to receive decent broadband from FWA    0
Number of premises with 30<300Mbit/s download speed             0
Number of premises with >=300Mbit/s download speed              0
Number of premises with 0<2Mbit/s download speed                0
Number of premises with 2<5Mbit/s download speed                0
Number of premises with 5<10Mbit/s download speed               0
Number of premises with 10<30Mbit/s download speed              0
% of premises with 30<300Mbit/s download speed                  0
% of premises with >=300Mbit/s download speed                   0
% of premises with 0<2Mbit/s download speed                     0
% of premises with 2<5Mbit/s download speed                     0
% of premises with 5<10Mbit/s download speed                    0
% of premises with 10<30Mbit/s download speed                   0
dtype: int64
unique to 2019
{'% of premises able to receive SFBB from FWA', 'Number of premises able to receive SFBB from FWA'}
unique to 2020
{'Number of premises with UFBB (100Mbit/s) availability', 'UFBB (100Mbit/s) availability (% premises)', 'Gigabit availability (% premises)', 'Number of premises with Gigabit availability'}
all uncommon columns
['Number of premises with Gigabit availability', 'UFBB (100Mbit/s) availability (% premises)', 'Gigabit availability (% premises)', 'Number of premises able to receive SFBB from FWA', '% of premises able to receive SFBB from FWA', 'Number of premises with UFBB (100Mbit/s) availability']
Pre 2020 columns
Post 2020 columns
382
379
374
374
374
(34, 36)
286    SOMERSET WEST AND TAUNTON
Name: laua_name, dtype: object
34    BOURNEMOUTH, CHRISTCHURCH AND POOLE
Name: laua_name, dtype: object
115    EAST SUFFOLK
204     MID SUFFOLK
364    WEST SUFFOLK
Name: laua_name, dtype: object
97    DORSET
Name: laua_name, dtype: object
338    TORFAEN
Name: laua_name, dtype: object
48    BUCKINGHAMSHIRE
Name: laua_name, dtype: object
226    NORTH NORTHAMPTONSHIRE
355     WEST NORTHAMPTONSHIRE
Name: laua_name, dtype: object
Series([], Name: laua_name, dtype: object)
3    ALLERDALE
Name: laua_name, dtype: object
80                      CORBY
111     EAST NORTHAMPTONSHIRE
175                 KETTERING
355            WELLINGBOROUGH
0      NORTH NORTHAMPTONSHIRE
Name: laua_name, dtype: object
['DAVENTRY', 'NORTHAMPTON', 'SOUTH NORTHAMPTONSHIRE']
91                   DAVENTRY
235               NORTHAMPTON
298    SOUTH NORTHAMPTONSHIRE
0       WEST NORTHAMPTONSHIRE
Name: laua_name, dtype: object
['AYLESBURY VALE', 'CHILTERN', 'SOUTH BUCKS', 'WYCOMBE']
13      AYLESBURY VALE
72            CHILTERN
288        SOUTH BUCKS
378            WYCOMBE
0      BUCKINGHAMSHIRE
Name: laua_name, dtype: object
['CORBY', 'EAST NORTHAMPTONSHIRE', 'KETTERING', 'WELLINGBOROUGH']
79                      CORBY
110     EAST NORTHAMPTONSHIRE
174                 KETTERING
353            WELLINGBOROUGH
0      NORTH NORTHAMPTONSHIRE
Name: laua_name, dtype: object
['DAVENTRY', 'NORTHAMPTON', 'SOUTH NORTHAMPTONSHIRE']
90                   DAVENTRY
234               NORTHAMPTON
296    SOUTH NORTHAMPTONSHIRE
0       WEST NORTHAMPTONSHIRE
Name: laua_name, dtype: object
374
374
374
374
374
       laua_name  Year
0  ABERDEEN CITY  2019
1  ABERDEENSHIRE  2019
2           ADUR  2019
3      ALLERDALE  2019
4   AMBER VALLEY  2019
       laua_name  Year
0  ABERDEEN CITY  2020
1  ABERDEENSHIRE  2020
2           ADUR  2020
3      ALLERDALE  2020
4   AMBER VALLEY  2020
       laua_name  Year
0  ABERDEEN CITY  2021
1  ABERDEENSHIRE  2021
2           ADUR  2021
3      ALLERDALE  2021
4   AMBER VALLEY  2021
       laua_name  Year
0  ABERDEEN CITY  2022
1  ABERDEENSHIRE  2022
2           ADUR  2022
3      ALLERDALE  2022
4   AMBER VALLEY  2022
       laua_name  Year
0  ABERDEEN CITY  2023
1  ABERDEENSHIRE  2023
2           ADUR  2023
3      ALLERDALE  2023
4   AMBER VALLEY  2023
MONGO_CONNECTION_STRING = mongodb://localhost:27017/
DB_NAME = OFCOM_FIXED
df_2019
df_2020
df_2023
df_2021
df_2022
Min Value: -5434.0
Max value: 155015.0
Min Value: -5434.0
Max value: 16839.0
374
374
5
[2019, 2020, 2021, 2022, 2023]
374
374
374
374
374

In [3]:
file_list = glob.glob('2023J_TMA02_data/Census/*.xlsx')
file_list

['2023J_TMA02_data/Census/nomis_2023_08_06_172146.xlsx',
 '2023J_TMA02_data/Census/nomis_2023_08_06_174635.xlsx',
 '2023J_TMA02_data/Census/nomis_2023_08_06_232642.xlsx']

The xlsx suffix shows these are excel files.  I 've already opened the files in excel and briefly investigated the results

In [4]:
for f in file_list:
    print(f,':',f.rsplit('/',1)[1][:-4])

2023J_TMA02_data/Census/nomis_2023_08_06_172146.xlsx : nomis_2023_08_06_172146.
2023J_TMA02_data/Census/nomis_2023_08_06_174635.xlsx : nomis_2023_08_06_174635.
2023J_TMA02_data/Census/nomis_2023_08_06_232642.xlsx : nomis_2023_08_06_232642.

In [5]:
dfs = {}
for f in file_list:
    year = f.rsplit('/',1)
    year =  'df_' + year[1]
    df = pd.read_excel(f, sheet_name=None)

    dfs[year] = df

Below shows all three excel files in the dfs collection

In [6]:
print(dfs.keys())

dict_keys(['df_nomis_2023_08_06_172146.xlsx', 'df_nomis_2023_08_06_174635.xlsx', 'df_nomis_2023_08_06_232642.xlsx'])

Below the sheets of each file are shown

In [7]:
for f in dfs.keys():
    print(dfs[f].keys())
    print()

dict_keys(['Aged 15 years and under', 'Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])

dict_keys(['Age 16 to 19', 'Age 20 to 21', 'Age 22 to 24', 'Age 25 to 29', 'Age 30 to 34', 'Age 35 to 39', 'Age 40 to 44', 'Age 45 to 49', 'Age 50 to 54', 'Age 55 to 59', 'Age 60 to 64', 'Age 65 and over'])

dict_keys(['Age 16 to 19', 'Age 20 to 24', 'Age 25 and over'])

In [8]:
print(dfs['df_nomis_2023_08_06_174635.xlsx'].keys())

dict_keys(['Age 16 to 19', 'Age 20 to 21', 'Age 22 to 24', 'Age 25 to 29', 'Age 30 to 34', 'Age 35 to 39', 'Age 40 to 44', 'Age 45 to 49', 'Age 50 to 54', 'Age 55 to 59', 'Age 60 to 64', 'Age 65 and over'])

In [9]:
dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21']

,DC6107EW - Economic Activity by sex by age,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ONS Crown Copyright Reserved [from Nomis on 6 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,population,All usual residents aged 16 and over,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,units,Persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,date,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
354,Torfaen,W06000020,563,854,11,39,380,1,167,96,64,67
355,Monmouthshire,W06000021,385,681,16,46,222,0,146,55,31,55
356,Newport,W06000022,1125,1097,25,37,674,3,843,161,81,139
357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21'][:12]

,DC6107EW - Economic Activity by sex by age,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ONS Crown Copyright Reserved [from Nomis on 6 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,population,All usual residents aged 16 and over,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,units,Persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,date,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,sex,All persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,age,Age 20 to 21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,local authority: district / unitary (prior to ...,NaN,Economically active: In employment: Employee: ...,Economically active: In employment: Employee: ...,Economically active: In employment: Self-emplo...,Economically active: In employment: Self-emplo...,Economically active: Unemployed (including ful...,Economically inactive: Retired,Economically inactive: Student (including full...,Economically inactive: Looking after home or f...,Economically inactive: Long-term sick or disabled,Economically inactive: Other
9,Darlington,E06000005,624,857,13,22,369,1,186,112,47,68
10,County Durham,E06000047,3177,3903,100,169,1808,9,5552,548,281,594
11,Hartlepool,E06000001,536,667,9,24,541,1,223,144,42,83

In [11]:
dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21'].tail()

,DC6107EW - Economic Activity by sex by age,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
354,Torfaen,W06000020,563,854,11,39,380,1,167,96,64,67
355,Monmouthshire,W06000021,385,681,16,46,222,0,146,55,31,55
356,Newport,W06000022,1125,1097,25,37,674,3,843,161,81,139
357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#convert the spreadsheets into dataframes and store in a dictionary
test_dfs = {}
for f in file_list:
    year = f.rsplit('/',1)
    year =  'df_' + year[1]
    df = pd.read_excel(f, sheet_name=None, skiprows=8, skipfooter=2)

    test_dfs[year] = df
    
#check the head and tail of each sheet    
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].head())
    print(i + ' tail')
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].tail())

Aged 15 years and under
                         Unnamed: 0 Unnamed: 1  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

                                          Unnamed: 2  \
0  Economically active (excluding full-time stude...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

                                          Unnamed: 3  \
0  Economically active (excluding full-time stude...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

                                          Unnamed: 4  \
0  Economically active and a full-time student: I...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

                                          Unnamed: 5  \
0  Economically active and a full-time student: U...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

                                          Unnamed: 6  \
0  Economically inactive (excluding full-time stu...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

                                      Unnamed: 7
0  Economically inactive and a full-time student
1                                              0
2                                              0
3                                              0
4                                              0
Aged 15 years and under tail
         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
327         Torfaen  W06000020          0          0          0          0
328   Monmouthshire  W06000021          0          0          0          0
329         Newport  W06000022          0          0          0          0
330           Powys  W06000023          0          0          0          0
331  Merthyr Tydfil  W06000024          0          0          0          0

    Unnamed: 6 Unnamed: 7
327          0          0
328          0          0
329          0          0
330          0          0
331          0          0
Aged 16 to 24 years
                         Unnamed: 0 Unnamed: 1  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

                                          Unnamed: 2  \
0  Economically active (excluding full-time stude...
1                                               3288
2                                               4811
3                                               4741
4                                               6766

                                          Unnamed: 3  \
0  Economically active (excluding full-time stude...
1                                                671
2                                               1079
3                                                916
4                                               1188

                                          Unnamed: 4  \
0  Economically active and a full-time student: I...
1                                                709
2                                               1656
3                                                932
4                                               1598

                                          Unnamed: 5  \
0  Economically active and a full-time student: U...
1                                                338
2                                                995
3                                                422
4                                                684

                                          Unnamed: 6  \
0  Economically inactive (excluding full-time stu...
1                                               1100
2                                               1916
3                                               1385
4                                               1945

                                      Unnamed: 7
0  Economically inactive and a full-time student
1                                           3018
2                                           6486
3                                           3795
4                                           5724
Aged 16 to 24 years tail
         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
327         Torfaen  W06000020       3645        608        622        270
328   Monmouthshire  W06000021       3169        417        601        194
329         Newport  W06000022       6003       1082       1358        617
330           Powys  W06000023       5059        502        785        191
331  Merthyr Tydfil  W06000024       2287        401        407        206

    Unnamed: 6 Unnamed: 7
327        936       2398
328        629       2471
329       1561       4902
330        876       3335
331        714       1697
Aged 25 to 34 years
                         Unnamed: 0 Unnamed: 1  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

                                          Unnamed: 2  \
0  Economically active (excluding full-time stude...
1                                               8105
2                                              13305
3                                              11260
4                                              18747

                                          Unnamed: 3  \
0  Economically active (excluding full-time stude...
1                                                618
2                                               1103
3                                                767
4                                               1179

                                          Unnamed: 4  \
0  Economically active and a full-time student: I...
1                                                111
2                                                642
3                                                231
4                                                365

                                          Unnamed: 5  \
0  Economically active and a full-time student: U...
1                                                 16
2                                                367
3                                                 35
4                                                 48

                                          Unnamed: 6  \
0  Economically inactive (excluding full-time stu...
1                                               2288
2                                               4176
3                                               2744
4                                               4072

                                      Unnamed: 7
0  Economically inactive and a full-time student
1                                            241
2                                           1049
3                                            332
4                                            642
Aged 25 to 34 years tail
         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
327         Torfaen  W06000020       9180        521        142         12
328   Monmouthshire  W06000021       7483        295        100         13
329         Newport  W06000022      18022       1029        314         55
330           Powys  W06000023      10801        439        109         15
331  Merthyr Tydfil  W06000024       5865        317        118         21

    Unnamed: 6 Unnamed: 7
327       2041        220
328       1177        159
329       3754        428
330       1670        196
331       1362        158
Aged 35 to 49 years
                         Unnamed: 0 Unnamed: 1  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

                                          Unnamed: 2  \
0  Economically active (excluding full-time stude...
1                                              11765
2                                              17550
3                                              17400
4                                              28683

                                          Unnamed: 3  \
0  Economically active (excluding full-time stude...
1                                                616
2                                               1094
3                                                812
4                                               1436

                                          Unnamed: 4  \
0  Economically active and a full-time student: I...
1                                                 62
2                                                252
3                                                130
4                                                252

                                          Unnamed: 5  \
0  Economically active and a full-time student: U...
1                                                 10
2                                                 64
3                                                 17
4                                                 22

                                          Unnamed: 6  \
0  Economically inactive (excluding full-time stu...
1                                               3361
2                                               6040
3                                               4234
4                                               6424

                                      Unnamed: 7
0  Economically inactive and a full-time student
1                                            133
2                                            347
3                                            212
4                                            375
Aged 35 to 49 years tail
         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
327         Torfaen  W06000020      12791        419         90          2
328   Monmouthshire  W06000021      13158        303         55          5
329         Newport  W06000022      24044        887        200         29
330           Powys  W06000023      17175        445         95         10
331  Merthyr Tydfil  W06000024       8454        293         56         10

    Unnamed: 6 Unnamed: 7
327       2848        126
328       2111        115
329       5368        279
330       2757        157
331       1981         60
Aged 50 to 64 years
                         Unnamed: 0 Unnamed: 1  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

                                          Unnamed: 2  \
0  Economically active (excluding full-time stude...
1                                              12347
2                                              16249
3                                              18712
4                                              26805

                                          Unnamed: 3  \
0  Economically active (excluding full-time stude...
1                                                686
2                                               1023
3                                                955
4                                               1235

                                          Unnamed: 4  \
0  Economically active and a full-time student: I...
1                                                 20
2                                                 33
3                                                 45
4                                                 51

                                          Unnamed: 5  \
0  Economically active and a full-time student: U...
1                                                  1
2                                                  5
3                                                  6
4                                                  4

                                          Unnamed: 6  \
0  Economically inactive (excluding full-time stu...
1                                               6903
2                                               9452
3                                              10437
4                                              12480

                                      Unnamed: 7
0  Economically inactive and a full-time student
1                                             48
2                                             63
3                                             75
4                                            100
Aged 50 to 64 years tail
         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
327         Torfaen  W06000020      12505        418         36          0
328   Monmouthshire  W06000021      15357        439         40          2
329         Newport  W06000022      20221        725         48          9
330           Powys  W06000023      21976        637         33          3
331  Merthyr Tydfil  W06000024       7548        282         19          1

    Unnamed: 6 Unnamed: 7
327       6086         44
328       5852         51
329       9333         93
330       8065         86
331       4270         41
Aged 65 years and over
                         Unnamed: 0 Unnamed: 1  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

                                          Unnamed: 2  \
0  Economically active (excluding full-time stude...
1                                               1339
2                                               1933
3                                               2169
4                                               3174

                                          Unnamed: 3  \
0  Economically active (excluding full-time stude...
1                                                 51
2                                                 87
3                                                 75
4                                                103

                                          Unnamed: 4  \
0  Economically active and a full-time student: I...
1                                                  1
2                                                  2
3                                                  4
4                                                  2

                                          Unnamed: 5  \
0  Economically active and a full-time student: U...
1                                                  0
2                                                  0
3                                                  0
4                                                  1

                                          Unnamed: 6  \
0  Economically inactive (excluding full-time stu...
1                                              16820
2                                              22131
3                                              29472
4                                              33868

                                      Unnamed: 7
0  Economically inactive and a full-time student
1                                             22
2                                             25
3                                             29
4                                             36
Aged 65 years and over tail
         Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
327         Torfaen  W06000020       1643         38          4          0
328   Monmouthshire  W06000021       2858         60          6          1
329         Newport  W06000022       2575         76          3          0
330           Powys  W06000023       5688         83          8          0
331  Merthyr Tydfil  W06000024        880         19          1          0

    Unnamed: 6 Unnamed: 7
327      17452         24
328      21086         28
329      24374         31
330      31297         44
331      10195         17

Below I grab the correct column names and rename the columns, the cell after next shows this has been successful

In [13]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    new_cols = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].loc[0].tolist()
    old_cols = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].columns
    new_cols[1] = 'laua_code'
    for j in range(len(old_cols)):
        test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].rename(columns= {old_cols[j]: new_cols[j]}, inplace =True)

In [14]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].head())
    print(i + ' tail')
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].tail())

Aged 15 years and under
   2022 local authorities: district  laua_code  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

  Economically active (excluding full-time students): In employment  \
0  Economically active (excluding full-time stude...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  Economically active (excluding full-time students): Unemployed  \
0  Economically active (excluding full-time stude...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  Economically active and a full-time student: In employment  \
0  Economically active and a full-time student: I...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  Economically active and a full-time student: Unemployed  \
0  Economically active and a full-time student: U...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  Economically inactive (excluding full-time students)  \
0  Economically inactive (excluding full-time stu...
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   Economically inactive and a full-time student
0  Economically inactive and a full-time student
1                                              0
2                                              0
3                                              0
4                                              0
Aged 15 years and under tail
    2022 local authorities: district  laua_code  \
327                          Torfaen  W06000020
328                    Monmouthshire  W06000021
329                          Newport  W06000022
330                            Powys  W06000023
331                   Merthyr Tydfil  W06000024

    Economically active (excluding full-time students): In employment  \
327                                                  0
328                                                  0
329                                                  0
330                                                  0
331                                                  0

    Economically active (excluding full-time students): Unemployed  \
327                                                  0
328                                                  0
329                                                  0
330                                                  0
331                                                  0

    Economically active and a full-time student: In employment  \
327                                                  0
328                                                  0
329                                                  0
330                                                  0
331                                                  0

    Economically active and a full-time student: Unemployed  \
327                                                  0
328                                                  0
329                                                  0
330                                                  0
331                                                  0

    Economically inactive (excluding full-time students)  \
327                                                  0
328                                                  0
329                                                  0
330                                                  0
331                                                  0

    Economically inactive and a full-time student
327                                             0
328                                             0
329                                             0
330                                             0
331                                             0
Aged 16 to 24 years
   2022 local authorities: district  laua_code  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

  Economically active (excluding full-time students): In employment  \
0  Economically active (excluding full-time stude...
1                                               3288
2                                               4811
3                                               4741
4                                               6766

  Economically active (excluding full-time students): Unemployed  \
0  Economically active (excluding full-time stude...
1                                                671
2                                               1079
3                                                916
4                                               1188

  Economically active and a full-time student: In employment  \
0  Economically active and a full-time student: I...
1                                                709
2                                               1656
3                                                932
4                                               1598

  Economically active and a full-time student: Unemployed  \
0  Economically active and a full-time student: U...
1                                                338
2                                                995
3                                                422
4                                                684

  Economically inactive (excluding full-time students)  \
0  Economically inactive (excluding full-time stu...
1                                               1100
2                                               1916
3                                               1385
4                                               1945

   Economically inactive and a full-time student
0  Economically inactive and a full-time student
1                                           3018
2                                           6486
3                                           3795
4                                           5724
Aged 16 to 24 years tail
    2022 local authorities: district  laua_code  \
327                          Torfaen  W06000020
328                    Monmouthshire  W06000021
329                          Newport  W06000022
330                            Powys  W06000023
331                   Merthyr Tydfil  W06000024

    Economically active (excluding full-time students): In employment  \
327                                               3645
328                                               3169
329                                               6003
330                                               5059
331                                               2287

    Economically active (excluding full-time students): Unemployed  \
327                                                608
328                                                417
329                                               1082
330                                                502
331                                                401

    Economically active and a full-time student: In employment  \
327                                                622
328                                                601
329                                               1358
330                                                785
331                                                407

    Economically active and a full-time student: Unemployed  \
327                                                270
328                                                194
329                                                617
330                                                191
331                                                206

    Economically inactive (excluding full-time students)  \
327                                                936
328                                                629
329                                               1561
330                                                876
331                                                714

    Economically inactive and a full-time student
327                                          2398
328                                          2471
329                                          4902
330                                          3335
331                                          1697
Aged 25 to 34 years
   2022 local authorities: district  laua_code  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

  Economically active (excluding full-time students): In employment  \
0  Economically active (excluding full-time stude...
1                                               8105
2                                              13305
3                                              11260
4                                              18747

  Economically active (excluding full-time students): Unemployed  \
0  Economically active (excluding full-time stude...
1                                                618
2                                               1103
3                                                767
4                                               1179

  Economically active and a full-time student: In employment  \
0  Economically active and a full-time student: I...
1                                                111
2                                                642
3                                                231
4                                                365

  Economically active and a full-time student: Unemployed  \
0  Economically active and a full-time student: U...
1                                                 16
2                                                367
3                                                 35
4                                                 48

  Economically inactive (excluding full-time students)  \
0  Economically inactive (excluding full-time stu...
1                                               2288
2                                               4176
3                                               2744
4                                               4072

   Economically inactive and a full-time student
0  Economically inactive and a full-time student
1                                            241
2                                           1049
3                                            332
4                                            642
Aged 25 to 34 years tail
    2022 local authorities: district  laua_code  \
327                          Torfaen  W06000020
328                    Monmouthshire  W06000021
329                          Newport  W06000022
330                            Powys  W06000023
331                   Merthyr Tydfil  W06000024

    Economically active (excluding full-time students): In employment  \
327                                               9180
328                                               7483
329                                              18022
330                                              10801
331                                               5865

    Economically active (excluding full-time students): Unemployed  \
327                                                521
328                                                295
329                                               1029
330                                                439
331                                                317

    Economically active and a full-time student: In employment  \
327                                                142
328                                                100
329                                                314
330                                                109
331                                                118

    Economically active and a full-time student: Unemployed  \
327                                                 12
328                                                 13
329                                                 55
330                                                 15
331                                                 21

    Economically inactive (excluding full-time students)  \
327                                               2041
328                                               1177
329                                               3754
330                                               1670
331                                               1362

    Economically inactive and a full-time student
327                                           220
328                                           159
329                                           428
330                                           196
331                                           158
Aged 35 to 49 years
   2022 local authorities: district  laua_code  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

  Economically active (excluding full-time students): In employment  \
0  Economically active (excluding full-time stude...
1                                              11765
2                                              17550
3                                              17400
4                                              28683

  Economically active (excluding full-time students): Unemployed  \
0  Economically active (excluding full-time stude...
1                                                616
2                                               1094
3                                                812
4                                               1436

  Economically active and a full-time student: In employment  \
0  Economically active and a full-time student: I...
1                                                 62
2                                                252
3                                                130
4                                                252

  Economically active and a full-time student: Unemployed  \
0  Economically active and a full-time student: U...
1                                                 10
2                                                 64
3                                                 17
4                                                 22

  Economically inactive (excluding full-time students)  \
0  Economically inactive (excluding full-time stu...
1                                               3361
2                                               6040
3                                               4234
4                                               6424

   Economically inactive and a full-time student
0  Economically inactive and a full-time student
1                                            133
2                                            347
3                                            212
4                                            375
Aged 35 to 49 years tail
    2022 local authorities: district  laua_code  \
327                          Torfaen  W06000020
328                    Monmouthshire  W06000021
329                          Newport  W06000022
330                            Powys  W06000023
331                   Merthyr Tydfil  W06000024

    Economically active (excluding full-time students): In employment  \
327                                              12791
328                                              13158
329                                              24044
330                                              17175
331                                               8454

    Economically active (excluding full-time students): Unemployed  \
327                                                419
328                                                303
329                                                887
330                                                445
331                                                293

    Economically active and a full-time student: In employment  \
327                                                 90
328                                                 55
329                                                200
330                                                 95
331                                                 56

    Economically active and a full-time student: Unemployed  \
327                                                  2
328                                                  5
329                                                 29
330                                                 10
331                                                 10

    Economically inactive (excluding full-time students)  \
327                                               2848
328                                               2111
329                                               5368
330                                               2757
331                                               1981

    Economically inactive and a full-time student
327                                           126
328                                           115
329                                           279
330                                           157
331                                            60
Aged 50 to 64 years
   2022 local authorities: district  laua_code  \
0  2022 local authorities: district        NaN
1                        Hartlepool  E06000001
2                     Middlesbrough  E06000002
3              Redcar and Cleveland  E06000003
4                  Stockton-on-Tees  E06000004

  Economically active (excluding full-time students): In employment  \
0  Economically active (excluding full-time stude...
1                                              12347
2                                              16249
3                                              18712
4                                              26805

  Economically active (excluding full-time students): Unemployed  \
0  Economically active (excluding full-time stude...
1                                                686
2                                               1023
3                                                955
4                                               1235

  Economically active and a full-time student: In employment  \
0  Economically active and a full-time student: I...
1                                                 20
2                                                 33
3                                                 45
4                                                 51

  Economically active and a full-time student: Unemployed  \
0  Economically active and a full-time student: U...
1                                                  1
2                                                  5
3                                                  6
4                                                  4


The output above shows that the columns have been successfully renamed.  I will now drop the first row from each and reset the indexes and I should have all the correct rows and column names for each excel sheet in the 2021 employment data

In [15]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].drop([0], inplace=True)
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].reset_index(inplace=True)

In [16]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].head())

Aged 15 years and under
   index 2022 local authorities: district  laua_code  \
0      1                       Hartlepool  E06000001
1      2                    Middlesbrough  E06000002
2      3             Redcar and Cleveland  E06000003
3      4                 Stockton-on-Tees  E06000004
4      5                       Darlington  E06000005

  Economically active (excluding full-time students): In employment  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  Economically active (excluding full-time students): Unemployed  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  Economically active and a full-time student: In employment  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  Economically active and a full-time student: Unemployed  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  Economically inactive (excluding full-time students)  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

  Economically inactive and a full-time student
0                                             0
1                                             0
2                                             0
3                                             0
4                                             0
Aged 16 to 24 years
   index 2022 local authorities: district  laua_code  \
0      1                       Hartlepool  E06000001
1      2                    Middlesbrough  E06000002
2      3             Redcar and Cleveland  E06000003
3      4                 Stockton-on-Tees  E06000004
4      5                       Darlington  E06000005

  Economically active (excluding full-time students): In employment  \
0                                               3288
1                                               4811
2                                               4741
3                                               6766
4                                               4284

  Economically active (excluding full-time students): Unemployed  \
0                                                671
1                                               1079
2                                                916
3                                               1188
4                                                697

  Economically active and a full-time student: In employment  \
0                                                709
1                                               1656
2                                                932
3                                               1598
4                                                881

  Economically active and a full-time student: Unemployed  \
0                                                338
1                                                995
2                                                422
3                                                684
4                                                334

  Economically inactive (excluding full-time students)  \
0                                               1100
1                                               1916
2                                               1385
3                                               1945
4                                                984

  Economically inactive and a full-time student
0                                          3018
1                                          6486
2                                          3795
3                                          5724
4                                          2788
Aged 25 to 34 years
   index 2022 local authorities: district  laua_code  \
0      1                       Hartlepool  E06000001
1      2                    Middlesbrough  E06000002
2      3             Redcar and Cleveland  E06000003
3      4                 Stockton-on-Tees  E06000004
4      5                       Darlington  E06000005

  Economically active (excluding full-time students): In employment  \
0                                               8105
1                                              13305
2                                              11260
3                                              18747
4                                              10394

  Economically active (excluding full-time students): Unemployed  \
0                                                618
1                                               1103
2                                                767
3                                               1179
4                                                593

  Economically active and a full-time student: In employment  \
0                                                111
1                                                642
2                                                231
3                                                365
4                                                162

  Economically active and a full-time student: Unemployed  \
0                                                 16
1                                                367
2                                                 35
3                                                 48
4                                                 17

  Economically inactive (excluding full-time students)  \
0                                               2288
1                                               4176
2                                               2744
3                                               4072
4                                               1962

  Economically inactive and a full-time student
0                                           241
1                                          1049
2                                           332
3                                           642
4                                           215
Aged 35 to 49 years
   index 2022 local authorities: district  laua_code  \
0      1                       Hartlepool  E06000001
1      2                    Middlesbrough  E06000002
2      3             Redcar and Cleveland  E06000003
3      4                 Stockton-on-Tees  E06000004
4      5                       Darlington  E06000005

  Economically active (excluding full-time students): In employment  \
0                                              11765
1                                              17550
2                                              17400
3                                              28683
4                                              16102

  Economically active (excluding full-time students): Unemployed  \
0                                                616
1                                               1094
2                                                812
3                                               1436
4                                                650

  Economically active and a full-time student: In employment  \
0                                                 62
1                                                252
2                                                130
3                                                252
4                                                118

  Economically active and a full-time student: Unemployed  \
0                                                 10
1                                                 64
2                                                 17
3                                                 22
4                                                 10

  Economically inactive (excluding full-time students)  \
0                                               3361
1                                               6040
2                                               4234
3                                               6424
4                                               3103

  Economically inactive and a full-time student
0                                           133
1                                           347
2                                           212
3                                           375
4                                           140
Aged 50 to 64 years
   index 2022 local authorities: district  laua_code  \
0      1                       Hartlepool  E06000001
1      2                    Middlesbrough  E06000002
2      3             Redcar and Cleveland  E06000003
3      4                 Stockton-on-Tees  E06000004
4      5                       Darlington  E06000005

  Economically active (excluding full-time students): In employment  \
0                                              12347
1                                              16249
2                                              18712
3                                              26805
4                                              15448

  Economically active (excluding full-time students): Unemployed  \
0                                                686
1                                               1023
2                                                955
3                                               1235
4                                                668

  Economically active and a full-time student: In employment  \
0                                                 20
1                                                 33
2                                                 45
3                                                 51
4                                                 32

  Economically active and a full-time student: Unemployed  \
0                                                  1
1                                                  5
2                                                  6
3                                                  4
4                                                  7

  Economically inactive (excluding full-time students)  \
0                                               6903
1                                               9452
2                                              10437
3                                              12480
4                                               6410

  Economically inactive and a full-time student
0                                            48
1                                            63
2                                            75
3                                           100
4                                            64
Aged 65 years and over
   index 2022 local authorities: district  laua_code  \
0      1                       Hartlepool  E06000001
1      2                    Middlesbrough  E06000002
2      3             Redcar and Cleveland  E06000003
3      4                 Stockton-on-Tees  E06000004
4      5                       Darlington  E06000005

  Economically active (excluding full-time students): In employment  \
0                                               1339
1                                               1933
2                                               2169
3                                               3174
4                                               1873

  Economically active (excluding full-time students): Unemployed  \
0                                                 51
1                                                 87
2                                                 75
3                                                103
4                                                 54

  Economically active and a full-time student: In employment  \
0                                                  1
1                                                  2
2                                                  4
3                                                  2
4                                                  1

  Economically active and a full-time student: Unemployed  \
0                                                  0
1                                                  0
2                                                  0
3                                                  1
4                                                  0

  Economically inactive (excluding full-time students)  \
0                                              16820
1                                              22131
2                                              29472
3                                              33868
4                                              20090

  Economically inactive and a full-time student
0                                            22
1                                            25
2                                            29
3                                            36
4                                            22

The above shows a new index column has been created we'll drop that, check again and move on

In [17]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].drop(['index'], axis=1, inplace=True)
    #check all dataframes are the same length
    print(len(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]))
    
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 50 to 64 years'].head()

331
331
331
331
331
331

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student
0,Hartlepool,E06000001,12347,686,20,1,6903,48
1,Middlesbrough,E06000002,16249,1023,33,5,9452,63
2,Redcar and Cleveland,E06000003,18712,955,45,6,10437,75
3,Stockton-on-Tees,E06000004,26805,1235,51,4,12480,100
4,Darlington,E06000005,15448,668,32,7,6410,64

Right now I'm getting somewhere i'll add the age group as a column as this will need to be a key value pair in the MongoDb collection.  I will also calculate some totals and add them as new columns like total residents, total unemployed, total in employment

In [18]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Age Group'] = i
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 15 years and under'].head()

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group
0,Hartlepool,E06000001,0,0,0,0,0,0,Aged 15 years and under
1,Middlesbrough,E06000002,0,0,0,0,0,0,Aged 15 years and under
2,Redcar and Cleveland,E06000003,0,0,0,0,0,0,Aged 15 years and under
3,Stockton-on-Tees,E06000004,0,0,0,0,0,0,Aged 15 years and under
4,Darlington,E06000005,0,0,0,0,0,0,Aged 15 years and under

In [19]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].dtypes)

2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment    object
Economically active (excluding full-time students): Unemployed       object
Economically active and a full-time student: In employment           object
Economically active and a full-time student: Unemployed              object
Economically inactive (excluding full-time students)                 object
Economically inactive and a full-time student                        object
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment    object
Economically active (excluding full-time students): Unemployed       object
Economically active and a full-time student: In employment           object
Economically active and a full-time student: Unemployed              object
Economically inactive (excluding full-time students)                 object
Economically inactive and a full-time student                        object
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment    object
Economically active (excluding full-time students): Unemployed       object
Economically active and a full-time student: In employment           object
Economically active and a full-time student: Unemployed              object
Economically inactive (excluding full-time students)                 object
Economically inactive and a full-time student                        object
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment    object
Economically active (excluding full-time students): Unemployed       object
Economically active and a full-time student: In employment           object
Economically active and a full-time student: Unemployed              object
Economically inactive (excluding full-time students)                 object
Economically inactive and a full-time student                        object
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment    object
Economically active (excluding full-time students): Unemployed       object
Economically active and a full-time student: In employment           object
Economically active and a full-time student: Unemployed              object
Economically inactive (excluding full-time students)                 object
Economically inactive and a full-time student                        object
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment    object
Economically active (excluding full-time students): Unemployed       object
Economically active and a full-time student: In employment           object
Economically active and a full-time student: Unemployed              object
Economically inactive (excluding full-time students)                 object
Economically inactive and a full-time student                        object
Age Group                                                            object
dtype: object

**THe cell above shows the data types are all objects, in order to work with the numerical data I shall have to change them to integer data types**

In [20]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    cols = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].columns
    
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i] = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].convert_dtypes(convert_string=False)

In [21]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].dtypes)

2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment     Int64
Economically active (excluding full-time students): Unemployed        Int64
Economically active and a full-time student: In employment            Int64
Economically active and a full-time student: Unemployed               Int64
Economically inactive (excluding full-time students)                  Int64
Economically inactive and a full-time student                         Int64
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment     Int64
Economically active (excluding full-time students): Unemployed        Int64
Economically active and a full-time student: In employment            Int64
Economically active and a full-time student: Unemployed               Int64
Economically inactive (excluding full-time students)                  Int64
Economically inactive and a full-time student                         Int64
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment     Int64
Economically active (excluding full-time students): Unemployed        Int64
Economically active and a full-time student: In employment            Int64
Economically active and a full-time student: Unemployed               Int64
Economically inactive (excluding full-time students)                  Int64
Economically inactive and a full-time student                         Int64
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment     Int64
Economically active (excluding full-time students): Unemployed        Int64
Economically active and a full-time student: In employment            Int64
Economically active and a full-time student: Unemployed               Int64
Economically inactive (excluding full-time students)                  Int64
Economically inactive and a full-time student                         Int64
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment     Int64
Economically active (excluding full-time students): Unemployed        Int64
Economically active and a full-time student: In employment            Int64
Economically active and a full-time student: Unemployed               Int64
Economically inactive (excluding full-time students)                  Int64
Economically inactive and a full-time student                         Int64
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment     Int64
Economically active (excluding full-time students): Unemployed        Int64
Economically active and a full-time student: In employment            Int64
Economically active and a full-time student: Unemployed               Int64
Economically inactive (excluding full-time students)                  Int64
Economically inactive and a full-time student                         Int64
Age Group                                                            object
dtype: object

**The cell below adds some columns which collect the data points in the original spreadsheet, this could be useful later as the 2011 and 2021 columns are different both in number and in definition.  By collecting the columns into totals direct comparisons can be made between the data from these years, I will also keep all of the existing columns.**

In [22]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    cols = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].columns[2:-1]   
    total = []
    active = []
    inactive = []
    employed = []
    for index, row in test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].iterrows():
        total.append(row[cols].sum())
        active.append(row[cols[:-2]].sum())
        inactive.append(row[cols[4:]].sum())
        employed.append(row[cols[0]] + row[cols[2]]) # the cols[2] here was initially cols[3] but that was incorrect 
                                                    #this is mentioned below
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Total Residents'] = total
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Total Active'] = active
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Total Inactive'] = inactive
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Total Employed'] = employed

The following two cells check to see if the changes made have been successful

In [23]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].head())

  2022 local authorities: district  laua_code  \
0                       Hartlepool  E06000001
1                    Middlesbrough  E06000002
2             Redcar and Cleveland  E06000003
3                 Stockton-on-Tees  E06000004
4                       Darlington  E06000005

   Economically active (excluding full-time students): In employment  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   Economically active (excluding full-time students): Unemployed  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   Economically active and a full-time student: In employment  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   Economically active and a full-time student: Unemployed  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   Economically inactive (excluding full-time students)  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   Economically inactive and a full-time student                Age Group  \
0                                              0  Aged 15 years and under
1                                              0  Aged 15 years and under
2                                              0  Aged 15 years and under
3                                              0  Aged 15 years and under
4                                              0  Aged 15 years and under

   Total Residents  Total Active  Total Inactive  Total Employed
0                0             0               0               0
1                0             0               0               0
2                0             0               0               0
3                0             0               0               0
4                0             0               0               0
  2022 local authorities: district  laua_code  \
0                       Hartlepool  E06000001
1                    Middlesbrough  E06000002
2             Redcar and Cleveland  E06000003
3                 Stockton-on-Tees  E06000004
4                       Darlington  E06000005

   Economically active (excluding full-time students): In employment  \
0                                               3288
1                                               4811
2                                               4741
3                                               6766
4                                               4284

   Economically active (excluding full-time students): Unemployed  \
0                                                671
1                                               1079
2                                                916
3                                               1188
4                                                697

   Economically active and a full-time student: In employment  \
0                                                709
1                                               1656
2                                                932
3                                               1598
4                                                881

   Economically active and a full-time student: Unemployed  \
0                                                338
1                                                995
2                                                422
3                                                684
4                                                334

   Economically inactive (excluding full-time students)  \
0                                               1100
1                                               1916
2                                               1385
3                                               1945
4                                                984

   Economically inactive and a full-time student            Age Group  \
0                                           3018  Aged 16 to 24 years
1                                           6486  Aged 16 to 24 years
2                                           3795  Aged 16 to 24 years
3                                           5724  Aged 16 to 24 years
4                                           2788  Aged 16 to 24 years

   Total Residents  Total Active  Total Inactive  Total Employed
0             9124          5006            4118            3997
1            16943          8541            8402            6467
2            12191          7011            5180            5673
3            17905         10236            7669            8364
4             9968          6196            3772            5165
  2022 local authorities: district  laua_code  \
0                       Hartlepool  E06000001
1                    Middlesbrough  E06000002
2             Redcar and Cleveland  E06000003
3                 Stockton-on-Tees  E06000004
4                       Darlington  E06000005

   Economically active (excluding full-time students): In employment  \
0                                               8105
1                                              13305
2                                              11260
3                                              18747
4                                              10394

   Economically active (excluding full-time students): Unemployed  \
0                                                618
1                                               1103
2                                                767
3                                               1179
4                                                593

   Economically active and a full-time student: In employment  \
0                                                111
1                                                642
2                                                231
3                                                365
4                                                162

   Economically active and a full-time student: Unemployed  \
0                                                 16
1                                                367
2                                                 35
3                                                 48
4                                                 17

   Economically inactive (excluding full-time students)  \
0                                               2288
1                                               4176
2                                               2744
3                                               4072
4                                               1962

   Economically inactive and a full-time student            Age Group  \
0                                            241  Aged 25 to 34 years
1                                           1049  Aged 25 to 34 years
2                                            332  Aged 25 to 34 years
3                                            642  Aged 25 to 34 years
4                                            215  Aged 25 to 34 years

   Total Residents  Total Active  Total Inactive  Total Employed
0            11379          8850            2529            8216
1            20642         15417            5225           13947
2            15369         12293            3076           11491
3            25053         20339            4714           19112
4            13343         11166            2177           10556
  2022 local authorities: district  laua_code  \
0                       Hartlepool  E06000001
1                    Middlesbrough  E06000002
2             Redcar and Cleveland  E06000003
3                 Stockton-on-Tees  E06000004
4                       Darlington  E06000005

   Economically active (excluding full-time students): In employment  \
0                                              11765
1                                              17550
2                                              17400
3                                              28683
4                                              16102

   Economically active (excluding full-time students): Unemployed  \
0                                                616
1                                               1094
2                                                812
3                                               1436
4                                                650

   Economically active and a full-time student: In employment  \
0                                                 62
1                                                252
2                                                130
3                                                252
4                                                118

   Economically active and a full-time student: Unemployed  \
0                                                 10
1                                                 64
2                                                 17
3                                                 22
4                                                 10

   Economically inactive (excluding full-time students)  \
0                                               3361
1                                               6040
2                                               4234
3                                               6424
4                                               3103

   Economically inactive and a full-time student            Age Group  \
0                                            133  Aged 35 to 49 years
1                                            347  Aged 35 to 49 years
2                                            212  Aged 35 to 49 years
3                                            375  Aged 35 to 49 years
4                                            140  Aged 35 to 49 years

   Total Residents  Total Active  Total Inactive  Total Employed
0            15947         12453            3494           11827
1            25347         18960            6387           17802
2            22805         18359            4446           17530
3            37192         30393            6799           28935
4            20123         16880            3243           16220
  2022 local authorities: district  laua_code  \
0                       Hartlepool  E06000001
1                    Middlesbrough  E06000002
2             Redcar and Cleveland  E06000003
3                 Stockton-on-Tees  E06000004
4                       Darlington  E06000005

   Economically active (excluding full-time students): In employment  \
0                                              12347
1                                              16249
2                                              18712
3                                              26805
4                                              15448

   Economically active (excluding full-time students): Unemployed  \
0                                                686
1                                               1023
2                                                955
3                                               1235
4                                                668

   Economically active and a full-time student: In employment  \
0                                                 20
1                                                 33
2                                                 45
3                                                 51
4                                                 32

   Economically active and a full-time student: Unemployed  \
0                                                  1
1                                                  5
2                                                  6
3                                                  4
4                                                  7

   Economically inactive (excluding full-time students)  \
0                                               6903
1                                               9452
2                                              10437
3                                              12480
4                                               6410

   Economically inactive and a full-time student            Age Group  \
0                                             48  Aged 50 to 64 years
1                                             63  Aged 50 to 64 years
2                                             75  Aged 50 to 64 years
3                                            100  Aged 50 to 64 years
4                                             64  Aged 50 to 64 years

   Total Residents  Total Active  Total Inactive  Total Employed
0            20005         13054            6951           12367
1            26825         17310            9515           16282
2            30230         19718           10512           18757
3            40675         28095           12580           26856
4            22629         16155            6474           15480
  2022 local authorities: district  laua_code  \
0                       Hartlepool  E06000001
1                    Middlesbrough  E06000002
2             Redcar and Cleveland  E06000003
3                 Stockton-on-Tees  E06000004
4                       Darlington  E06000005

   Economically active (excluding full-time students): In employment  \
0                                               1339
1                                               1933
2                                               2169
3                                               3174
4                                               1873

   Economically active (excluding full-time students): Unemployed  \
0                                                 51
1                                                 87
2                                                 75
3                                                103
4                                                 54

   Economically active and a full-time student: In employment  \
0                                                  1
1                                                  2
2                                                  4
3                                                  2
4                                                  1

   Economically active and a full-time student: Unemployed  \
0                                                  0
1                                                  0
2                                                  0
3                                                  1
4                                                  0

   Economically inactive (excluding full-time students)  \
0                                              16820
1                                              22131
2                                              29472
3                                              33868
4                                              20090

   Economically inactive and a full-time student               Age Group  \
0                                             22  Aged 65 years and over
1                                             25  Aged 65 years and over
2                                             29  Aged 65 years and over
3                                             36  Aged 65 years and over
4                                             22  Aged 65 years and over

   Total Residents  Total Active  Total Inactive  Total Employed
0            18233          1391           16842            1340
1            24178          2022           22156            1935
2            31749          2248           29501            2173
3            37184          3280           33904            3176
4            22040          1928           20112            1874

In [24]:
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years']

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed
0,Hartlepool,E06000001,3288,671,709,338,1100,3018,Aged 16 to 24 years,9124,5006,4118,3997
1,Middlesbrough,E06000002,4811,1079,1656,995,1916,6486,Aged 16 to 24 years,16943,8541,8402,6467
2,Redcar and Cleveland,E06000003,4741,916,932,422,1385,3795,Aged 16 to 24 years,12191,7011,5180,5673
3,Stockton-on-Tees,E06000004,6766,1188,1598,684,1945,5724,Aged 16 to 24 years,17905,10236,7669,8364
4,Darlington,E06000005,4284,697,881,334,984,2788,Aged 16 to 24 years,9968,6196,3772,5165
...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,Torfaen,W06000020,3645,608,622,270,936,2398,Aged 16 to 24 years,8479,5145,3334,4267
327,Monmouthshire,W06000021,3169,417,601,194,629,2471,Aged 16 to 24 years,7481,4381,3100,3770
328,Newport,W06000022,6003,1082,1358,617,1561,4902,Aged 16 to 24 years,15523,9060,6463,7361
329,Powys,W06000023,5059,502,785,191,876,3335,Aged 16 to 24 years,10748,6537,4211,5844
330,Merthyr Tydfil,W06000024,2287,401,407,206,714,1697,Aged 16 to 24 years,5712,3301,2411,2694

Now i'll check that the calculations have been done correctly by testing the top rows figures

In [25]:
3288+671+709+338 +1100 + 3018 #expecting 9124 as in df

9124

In [26]:
3288+671+709+338 #expecting 5006 as in the df

5006

In [27]:
1100 + 3018 # expecting 4118 as in the df

4118

In [28]:
3288 + 709 #expecting 3626 as in df

3997

Ah right now we have an issue the above output is 3997 which means the figure in the df has been calculated wrongly, I'll change the code used to calculate this figure and check the df again to see if the result is 3997 in the total employed column

In [29]:
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years'].head()

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed
0,Hartlepool,E06000001,3288,671,709,338,1100,3018,Aged 16 to 24 years,9124,5006,4118,3997
1,Middlesbrough,E06000002,4811,1079,1656,995,1916,6486,Aged 16 to 24 years,16943,8541,8402,6467
2,Redcar and Cleveland,E06000003,4741,916,932,422,1385,3795,Aged 16 to 24 years,12191,7011,5180,5673
3,Stockton-on-Tees,E06000004,6766,1188,1598,684,1945,5724,Aged 16 to 24 years,17905,10236,7669,8364
4,Darlington,E06000005,4284,697,881,334,984,2788,Aged 16 to 24 years,9968,6196,3772,5165

Im happy with the above I'll now try to create a dataframe containing data from all of the files

In [30]:
combined_2021_df = test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 15 years and under']

In [31]:
combined_2021_df

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed
0,Hartlepool,E06000001,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
1,Middlesbrough,E06000002,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
2,Redcar and Cleveland,E06000003,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
3,Stockton-on-Tees,E06000004,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
4,Darlington,E06000005,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,Torfaen,W06000020,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
327,Monmouthshire,W06000021,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
328,Newport,W06000022,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
329,Powys,W06000023,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
330,Merthyr Tydfil,W06000024,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0

In [32]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    if i != 'Aged 15 years and under':
        combined_2021_df = pd.concat([test_dfs['df_nomis_2023_08_06_172146.xlsx'][i], combined_2021_df])

Check the above has the right amount of rows (6 dfs of 331 rows)

In [33]:
1986/6

331.0

In [34]:
combined_2021_df['2022 local authorities: district'] = combined_2021_df['2022 local authorities: district'].str.upper()

Above I've converted the district names to upper case as this is how they are in the fixed broadband data.  I'll now add the year column which will be required as a key-value in the MongoDb instance

In [35]:
combined_2021_df['Year'] = 2021

In [36]:
combined_2021_df

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed,Year
0,HARTLEPOOL,E06000001,1339,51,1,0,16820,22,Aged 65 years and over,18233,1391,16842,1340,2021
1,MIDDLESBROUGH,E06000002,1933,87,2,0,22131,25,Aged 65 years and over,24178,2022,22156,1935,2021
2,REDCAR AND CLEVELAND,E06000003,2169,75,4,0,29472,29,Aged 65 years and over,31749,2248,29501,2173,2021
3,STOCKTON-ON-TEES,E06000004,3174,103,2,1,33868,36,Aged 65 years and over,37184,3280,33904,3176,2021
4,DARLINGTON,E06000005,1873,54,1,0,20090,22,Aged 65 years and over,22040,1928,20112,1874,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,TORFAEN,W06000020,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0,2021
327,MONMOUTHSHIRE,W06000021,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0,2021
328,NEWPORT,W06000022,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0,2021
329,POWYS,W06000023,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0,2021
330,MERTHYR TYDFIL,W06000024,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0,2021

In [37]:
#check for null values
combined_2021_df.isna().sum()

2022 local authorities: district                                     0
laua_code                                                            0
Economically active (excluding full-time students): In employment    0
Economically active (excluding full-time students): Unemployed       0
Economically active and a full-time student: In employment           0
Economically active and a full-time student: Unemployed              0
Economically inactive (excluding full-time students)                 0
Economically inactive and a full-time student                        0
Age Group                                                            0
Total Residents                                                      0
Total Active                                                         0
Total Inactive                                                       0
Total Employed                                                       0
Year                                                                 0
dtype: int64

I'm happy that the above data frame contains a row for each age group and local authority for the year 2021,  I will now attempt to do the same with the 2011 data, making sure to amalgamate the local authorities to match those in the 2021 data

In [38]:
a = test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years']['2022 local authorities: district'].tolist()
print(a)

['Hartlepool', 'Middlesbrough', 'Redcar and Cleveland', 'Stockton-on-Tees', 'Darlington', 'County Durham', 'Northumberland', 'Newcastle upon Tyne', 'North Tyneside', 'South Tyneside', 'Sunderland', 'Gateshead', 'Halton', 'Warrington', 'Blackburn with Darwen', 'Blackpool', 'Cheshire East', 'Cheshire West and Chester', 'Allerdale', 'Barrow-in-Furness', 'Carlisle', 'Copeland', 'Eden', 'South Lakeland', 'Burnley', 'Chorley', 'Fylde', 'Hyndburn', 'Lancaster', 'Pendle', 'Preston', 'Ribble Valley', 'Rossendale', 'South Ribble', 'West Lancashire', 'Wyre', 'Bolton', 'Bury', 'Manchester', 'Oldham', 'Rochdale', 'Salford', 'Stockport', 'Tameside', 'Trafford', 'Wigan', 'Knowsley', 'Liverpool', 'St. Helens', 'Sefton', 'Wirral', 'Kingston upon Hull, City of', 'East Riding of Yorkshire', 'North East Lincolnshire', 'North Lincolnshire', 'York', 'Craven', 'Hambleton', 'Harrogate', 'Richmondshire', 'Ryedale', 'Scarborough', 'Selby', 'Barnsley', 'Doncaster', 'Rotherham', 'Sheffield', 'Bradford', 'Calderdale', 'Kirklees', 'Leeds', 'Wakefield', 'Derby', 'Leicester', 'Rutland', 'Nottingham', 'North Northamptonshire', 'West Northamptonshire', 'Amber Valley', 'Bolsover', 'Chesterfield', 'Derbyshire Dales', 'Erewash', 'High Peak', 'North East Derbyshire', 'South Derbyshire', 'Blaby', 'Charnwood', 'Harborough', 'Hinckley and Bosworth', 'Melton', 'North West Leicestershire', 'Oadby and Wigston', 'Boston', 'East Lindsey', 'Lincoln', 'North Kesteven', 'South Holland', 'South Kesteven', 'West Lindsey', 'Ashfield', 'Bassetlaw', 'Broxtowe', 'Gedling', 'Mansfield', 'Newark and Sherwood', 'Rushcliffe', 'Herefordshire, County of', 'Telford and Wrekin', 'Stoke-on-Trent', 'Shropshire', 'Cannock Chase', 'East Staffordshire', 'Lichfield', 'Newcastle-under-Lyme', 'South Staffordshire', 'Stafford', 'Staffordshire Moorlands', 'Tamworth', 'North Warwickshire', 'Nuneaton and Bedworth', 'Rugby', 'Stratford-on-Avon', 'Warwick', 'Bromsgrove', 'Malvern Hills', 'Redditch', 'Worcester', 'Wychavon', 'Wyre Forest', 'Birmingham', 'Coventry', 'Dudley', 'Sandwell', 'Solihull', 'Walsall', 'Wolverhampton', 'Peterborough', 'Luton', 'Southend-on-Sea', 'Thurrock', 'Bedford', 'Central Bedfordshire', 'Cambridge', 'East Cambridgeshire', 'Fenland', 'Huntingdonshire', 'South Cambridgeshire', 'Basildon', 'Braintree', 'Brentwood', 'Castle Point', 'Chelmsford', 'Colchester', 'Epping Forest', 'Harlow', 'Maldon', 'Rochford', 'Tendring', 'Uttlesford', 'Broxbourne', 'Dacorum', 'Hertsmere', 'North Hertfordshire', 'Three Rivers', 'Watford', 'Breckland', 'Broadland', 'Great Yarmouth', "King's Lynn and West Norfolk", 'North Norfolk', 'Norwich', 'South Norfolk', 'Babergh', 'Ipswich', 'Mid Suffolk', 'St Albans', 'Welwyn Hatfield', 'East Hertfordshire', 'Stevenage', 'East Suffolk', 'West Suffolk', 'City of London', 'Barking and Dagenham', 'Barnet', 'Bexley', 'Brent', 'Bromley', 'Camden', 'Croydon', 'Ealing', 'Enfield', 'Greenwich', 'Hackney', 'Hammersmith and Fulham', 'Haringey', 'Harrow', 'Havering', 'Hillingdon', 'Hounslow', 'Islington', 'Kensington and Chelsea', 'Kingston upon Thames', 'Lambeth', 'Lewisham', 'Merton', 'Newham', 'Redbridge', 'Richmond upon Thames', 'Southwark', 'Sutton', 'Tower Hamlets', 'Waltham Forest', 'Wandsworth', 'Westminster', 'Medway', 'Bracknell Forest', 'West Berkshire', 'Reading', 'Slough', 'Windsor and Maidenhead', 'Wokingham', 'Milton Keynes', 'Brighton and Hove', 'Portsmouth', 'Southampton', 'Isle of Wight', 'Buckinghamshire', 'Eastbourne', 'Hastings', 'Lewes', 'Rother', 'Wealden', 'Basingstoke and Deane', 'East Hampshire', 'Eastleigh', 'Fareham', 'Gosport', 'Hart', 'Havant', 'New Forest', 'Rushmoor', 'Test Valley', 'Winchester', 'Ashford', 'Canterbury', 'Dartford', 'Dover', 'Gravesham', 'Maidstone', 'Sevenoaks', 'Folkestone and Hythe', 'Swale', 'Thanet', 'Tonbridge and Malling', 'Tunbridge Wells', 'Cherwell', 'Oxford', 'South Oxfordshire', 'Vale of White Horse', 'West Oxfordshire', 'Elmbridge', 'Epsom and Ewell', 'Guildford', 'Mole Valley', 'Reigate and Banstead', 'Runnymede', 'Spelthorne', 'Surrey Heath', 'Tandridge', 'Waverley', 'Woking', 'Adur', 'Arun', 'Chichester', 'Crawley', 'Horsham', 'Mid Sussex', 'Worthing', 'Bath and North East Somerset', 'Bristol, City of', 'North Somerset', 'South Gloucestershire', 'Plymouth', 'Torbay', 'Swindon', 'Cornwall', 'Isles of Scilly', 'Wiltshire', 'Bournemouth, Christchurch and Poole', 'Dorset', 'East Devon', 'Exeter', 'Mid Devon', 'North Devon', 'South Hams', 'Teignbridge', 'Torridge', 'West Devon', 'Cheltenham', 'Cotswold', 'Forest of Dean', 'Gloucester', 'Stroud', 'Tewkesbury', 'Mendip', 'Sedgemoor', 'South Somerset', 'Somerset West and Taunton', 'Isle of Anglesey', 'Gwynedd', 'Conwy', 'Denbighshire', 'Flintshire', 'Wrexham', 'Ceredigion', 'Pembrokeshire', 'Carmarthenshire', 'Swansea', 'Neath Port Talbot', 'Bridgend', 'Vale of Glamorgan', 'Cardiff', 'Rhondda Cynon Taff', 'Caerphilly', 'Blaenau Gwent', 'Torfaen', 'Monmouthshire', 'Newport', 'Powys', 'Merthyr Tydfil']

# Cleaning the 2011 data

The first few steps will be the same as with the 2021 data, i'll rename the columns and drop the meta rows

In [39]:
#check the head and tail of each sheet as before
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].head())
    print(i + ' tail')
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].tail())

Age 16 to 19
                                          Unnamed: 0 Unnamed: 1  \
0  local authority: district / unitary (prior to ...        NaN
1                                         Darlington  E06000005
2                                      County Durham  E06000047
3                                         Hartlepool  E06000001
4                                      Middlesbrough  E06000002

                                          Unnamed: 2  \
0  Economically active: In employment: Employee: ...
1                                               1246
2                                               4930
3                                                884
4                                               1542

                                          Unnamed: 3  \
0  Economically active: In employment: Employee: ...
1                                                619
2                                               3344
3                                                539
4                                                751

                                          Unnamed: 4  \
0  Economically active: In employment: Self-emplo...
1                                                 27
2                                                 85
3                                                 12
4                                                 22

                                          Unnamed: 5  \
0  Economically active: In employment: Self-emplo...
1                                                 16
2                                                 97
3                                                  8
4                                                 23

                                          Unnamed: 6  \
0  Economically active: Unemployed (including ful...
1                                                827
2                                               3854
3                                                915
4                                               1460

                       Unnamed: 7  \
0  Economically inactive: Retired
1                               1
2                              12
3                               1
4                               1

                                          Unnamed: 8  \
0  Economically inactive: Student (including full...
1                                               2109
2                                              13699
3                                               2382
4                                               4039

                                          Unnamed: 9  \
0  Economically inactive: Looking after home or f...
1                                                 77
2                                                397
3                                                112
4                                                143

                                         Unnamed: 10  \
0  Economically inactive: Long-term sick or disabled
1                                                 36
2                                                214
3                                                 31
4                                                 52

                    Unnamed: 11
0  Economically inactive: Other
1                           120
2                           753
3                           137
4                           220
Age 16 to 19 tail
        Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
344     Caerphilly  W06000018       1579       1149         24         29
345  Blaenau Gwent  W06000019        657        438          3          9
346        Torfaen  W06000020       1086        720         12         23
347  Monmouthshire  W06000021       1086        497         17         28
348        Newport  W06000022       1783        862         22         27

    Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11
344       1412          1       4490        118          69         200
345        638          1       1786         75          36         135
346        699          3       2089         81          45         112
347        510          4       2262         43          25         106
348       1293          5       3584         98          72         249
Age 20 to 21
                                          Unnamed: 0 Unnamed: 1  \
0  local authority: district / unitary (prior to ...        NaN
1                                         Darlington  E06000005
2                                      County Durham  E06000047
3                                         Hartlepool  E06000001
4                                      Middlesbrough  E06000002

                                          Unnamed: 2  \
0  Economically active: In employment: Employee: ...
1                                                624
2                                               3177
3                                                536
4                                               1223

                                          Unnamed: 3  \
0  Economically active: In employment: Employee: ...
1                                                857
2                                               3903
3                                                667
4                                                907

                                          Unnamed: 4  \
0  Economically active: In employment: Self-emplo...
1                                                 13
2                                                100
3                                                  9
4                                                 38

                                          Unnamed: 5  \
0  Economically active: In employment: Self-emplo...
1                                                 22
2                                                169
3                                                 24
4                                                 42

                                          Unnamed: 6  \
0  Economically active: Unemployed (including ful...
1                                                369
2                                               1808
3                                                541
4                                                927

                       Unnamed: 7  \
0  Economically inactive: Retired
1                               1
2                               9
3                               1
4                               4

                                          Unnamed: 8  \
0  Economically inactive: Student (including full...
1                                                186
2                                               5552
3                                                223
4                                               1280

                                          Unnamed: 9  \
0  Economically inactive: Looking after home or f...
1                                                112
2                                                548
3                                                144
4                                                206

                                         Unnamed: 10  \
0  Economically inactive: Long-term sick or disabled
1                                                 47
2                                                281
3                                                 42
4                                                 82

                    Unnamed: 11
0  Economically inactive: Other
1                            68
2                           594
3                            83
4                           185
Age 20 to 21 tail
        Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
344     Caerphilly  W06000018        873       1552         25         82
345  Blaenau Gwent  W06000019        396        582          7         35
346        Torfaen  W06000020        563        854         11         39
347  Monmouthshire  W06000021        385        681         16         46
348        Newport  W06000022       1125       1097         25         37

    Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11
344        750          2        388        219         111         147
345        386          5        165        118          46          83
346        380          1        167         96          64          67
347        222          0        146         55          31          55
348        674          3        843        161          81         139
Age 22 to 24
                                          Unnamed: 0 Unnamed: 1  \
0  local authority: district / unitary (prior to ...        NaN
1                                         Darlington  E06000005
2                                      County Durham  E06000047
3                                         Hartlepool  E06000001
4                                      Middlesbrough  E06000002

                                          Unnamed: 2  \
0  Economically active: In employment: Employee: ...
1                                                737
2                                               3436
3                                                743
4                                               1411

                                          Unnamed: 3  \
0  Economically active: In employment: Employee: ...
1                                               1964
2                                               8623
3                                               1493
4                                               2213

                                          Unnamed: 4  \
0  Economically active: In employment: Self-emplo...
1                                                 35
2                                                178
3                                                 33
4                                                 62

                                          Unnamed: 5  \
0  Economically active: In employment: Self-emplo...
1                                                 81
2                                                427
3                                                 93
4                                                119

                                          Unnamed: 6  \
0  Economically active: Unemployed (including ful...
1                                                451
2                                               1967
3                                                641
4                                               1106

                       Unnamed: 7  \
0  Economically inactive: Retired
1                               1
2                              15
3                               2
4                               2

                                          Unnamed: 8  \
0  Economically inactive: Student (including full...
1                                                106
2                                               2185
3                                                132
4                                                980

                                          Unnamed: 9  \
0  Economically inactive: Looking after home or f...
1                                                198
2                                               1000
3                                                287
4                                                470

                                         Unnamed: 10  \
0  Economically inactive: Long-term sick or disabled
1                                                 79
2                                                555
3                                                110
4                                                169

                    Unnamed: 11
0  Economically inactive: Other
1                           120
2                           628
3                           151
4                           264
Age 22 to 24 tail
        Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
344     Caerphilly  W06000018       1182       3325         48        202
345  Blaenau Gwent  W06000019        498       1311         15         63
346        Torfaen  W06000020        653       1653         24         73
347  Monmouthshire  W06000021        486       1381         33        111
348        Newport  W06000022       1246       2593         50        126

    Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11
344        809          5        282        421         213         184
345        406          4         78        193         117         128
346        364          2        122        234         129          92
347        227          2        136        126          70         102
348        714          3        457        328         119         220
Age 25 to 29
                                          Unnamed: 0 Unnamed: 1  \
0  local authority: district / unitary (prior to ...        NaN
1                                         Darlington  E06000005
2                                      County Durham  E06000047
3                                         Hartlepool  E06000001
4                                      Middlesbrough  E06000002

                                          Unnamed: 2  \
0  Economically active: In employment: Employee: ...
1                                               1082
2                                               4790
3                                               1012
4                                               1741

                                          Unnamed: 3  \
0  Economically active: In employment: Employee: ...
1                                               3747
2                                              17001
3                                               2650
4                                               4186

                                          Unnamed: 4  \
0  Economically active: In employment: Self-emplo...
1                                                 96
2                                                433
3                                                 76
4                                                134

                                          Unnamed: 5  \
0  Economically active: In employment: Self-emplo...
1                                                226
2                                               1127
3                                                166
4                                                304

                                          Unnamed: 6  \
0  Economically active: Unemployed (including ful...
1                                                585
2                                               2369
3                                                701
4                                               1205

                       Unnamed: 7  \
0  Economically inactive: Retired
1                               3
2                              18
3                               4
4                               4

                                          Unnamed: 8  \
0  Economically inactive: Student (including full...
1                                                112
2                                               1061
3                                                 96
4                                                515

                                          Unnamed: 9  \
0  Economically inactive: Looking after home or f...
1                                                426
2                                               1869
3                                                509
4                                                899

                                         Unnamed: 10  \
0  Economically inactive: Long-term sick or disabled
1                                                189
2                                               1162
3                                                215
4                                                353

                    Unnamed: 11
0  Economically inactive: Other
1                           141
2                           798
3                           193
4                           424
Age 25 to 29 tail
        Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
344     Caerphilly  W06000018       1722       6158        124        453
345  Blaenau Gwent  W06000019        674       2131         50        147
346        Torfaen  W06000020        918       3051         49        204
347  Monmouthshire  W06000021        529       2158         85        233
348        Newport  W06000022       1604       4843        119        341

    Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11
344        982          5        200        826         461         291
345        509          5         62        346         207         153
346        473          5         99        439         220         116
347        237          2         68        221         131         148
348        872          6        269        727         336         289
Age 30 to 34
                                          Unnamed: 0 Unnamed: 1  \
0  local authority: district / unitary (prior to ...        NaN
1                                         Darlington  E06000005
2                                      County Durham  E06000047
3                                         Hartlepool  E06000001
4                                      Middlesbrough  E06000002

                                          Unnamed: 2  \
0  Economically active: In employment: Employee: ...
1                                               1163
2                                               4885
3                                                946
4                                               1464

                                          Unnamed: 3  \
0  Economically active: In employment: Employee: ...
1                                               3490
2                                              15460
3                                               2328
4                                               3461

                                          Unnamed: 4  \
0  Economically active: In employment: Self-emplo...
1                                                128
2                                                531
3                                                 99
4                                                232

                                          Unnamed: 5  \
0  Economically active: In employment: Self-emplo...
1                                                331
2                                               1444
3                                                211
4                                                364

                                          Unnamed: 6  \
0  Economically active: Unemployed (including ful...
1                                                393
2                                               1644
3                                                568
4                                                882

                       Unnamed: 7  \
0  Economically inactive: Retired
1                               5
2                              17
3                               5
4                               8

                                          Unnamed: 8  \
0  Economically inactive: Student (including full...
1                                                 66
2                                                449
3                                                 55
4                                                261

                                          Unnamed: 9  \
0  Economically inactive: Looking after home or f...
1                                                460
2                                               1729
3                                                439
4                                                829


In [40]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    new_cols = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].loc[0].tolist()
    old_cols = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].columns
    new_cols[1] = 'laua_code'
    for j in range(len(old_cols)):
        test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].rename(columns= {old_cols[j]: new_cols[j]}, inplace =True)

In [41]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].head())
    print(i + ' tail')
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].tail())

Age 16 to 19
  local authority: district / unitary (prior to April 2015)  laua_code  \
0  local authority: district / unitary (prior to ...               NaN
1                                         Darlington         E06000005
2                                      County Durham         E06000047
3                                         Hartlepool         E06000001
4                                      Middlesbrough         E06000002

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0  Economically active: In employment: Employee: ...
1                                               1246
2                                               4930
3                                                884
4                                               1542

  Economically active: In employment: Employee: Full-time (including full-time students)  \
0  Economically active: In employment: Employee: ...
1                                                619
2                                               3344
3                                                539
4                                                751

  Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0  Economically active: In employment: Self-emplo...
1                                                 27
2                                                 85
3                                                 12
4                                                 22

  Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0  Economically active: In employment: Self-emplo...
1                                                 16
2                                                 97
3                                                  8
4                                                 23

  Economically active: Unemployed (including full-time students)  \
0  Economically active: Unemployed (including ful...
1                                                827
2                                               3854
3                                                915
4                                               1460

   Economically inactive: Retired  \
0  Economically inactive: Retired
1                               1
2                              12
3                               1
4                               1

  Economically inactive: Student (including full-time students)  \
0  Economically inactive: Student (including full...
1                                               2109
2                                              13699
3                                               2382
4                                               4039

  Economically inactive: Looking after home or family  \
0  Economically inactive: Looking after home or f...
1                                                 77
2                                                397
3                                                112
4                                                143

   Economically inactive: Long-term sick or disabled  \
0  Economically inactive: Long-term sick or disabled
1                                                 36
2                                                214
3                                                 31
4                                                 52

   Economically inactive: Other
0  Economically inactive: Other
1                           120
2                           753
3                           137
4                           220
Age 16 to 19 tail
    local authority: district / unitary (prior to April 2015)  laua_code  \
344                                         Caerphilly         W06000018
345                                      Blaenau Gwent         W06000019
346                                            Torfaen         W06000020
347                                      Monmouthshire         W06000021
348                                            Newport         W06000022

    Economically active: In employment: Employee: Part-time (including full-time students)  \
344                                               1579
345                                                657
346                                               1086
347                                               1086
348                                               1783

    Economically active: In employment: Employee: Full-time (including full-time students)  \
344                                               1149
345                                                438
346                                                720
347                                                497
348                                                862

    Economically active: In employment: Self-employed: Part-time (including full-time students)  \
344                                                 24
345                                                  3
346                                                 12
347                                                 17
348                                                 22

    Economically active: In employment: Self-employed: Full-time (including full-time students)  \
344                                                 29
345                                                  9
346                                                 23
347                                                 28
348                                                 27

    Economically active: Unemployed (including full-time students)  \
344                                               1412
345                                                638
346                                                699
347                                                510
348                                               1293

    Economically inactive: Retired  \
344                              1
345                              1
346                              3
347                              4
348                              5

    Economically inactive: Student (including full-time students)  \
344                                               4490
345                                               1786
346                                               2089
347                                               2262
348                                               3584

    Economically inactive: Looking after home or family  \
344                                                118
345                                                 75
346                                                 81
347                                                 43
348                                                 98

    Economically inactive: Long-term sick or disabled  \
344                                                69
345                                                36
346                                                45
347                                                25
348                                                72

    Economically inactive: Other
344                          200
345                          135
346                          112
347                          106
348                          249
Age 20 to 21
  local authority: district / unitary (prior to April 2015)  laua_code  \
0  local authority: district / unitary (prior to ...               NaN
1                                         Darlington         E06000005
2                                      County Durham         E06000047
3                                         Hartlepool         E06000001
4                                      Middlesbrough         E06000002

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0  Economically active: In employment: Employee: ...
1                                                624
2                                               3177
3                                                536
4                                               1223

  Economically active: In employment: Employee: Full-time (including full-time students)  \
0  Economically active: In employment: Employee: ...
1                                                857
2                                               3903
3                                                667
4                                                907

  Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0  Economically active: In employment: Self-emplo...
1                                                 13
2                                                100
3                                                  9
4                                                 38

  Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0  Economically active: In employment: Self-emplo...
1                                                 22
2                                                169
3                                                 24
4                                                 42

  Economically active: Unemployed (including full-time students)  \
0  Economically active: Unemployed (including ful...
1                                                369
2                                               1808
3                                                541
4                                                927

   Economically inactive: Retired  \
0  Economically inactive: Retired
1                               1
2                               9
3                               1
4                               4

  Economically inactive: Student (including full-time students)  \
0  Economically inactive: Student (including full...
1                                                186
2                                               5552
3                                                223
4                                               1280

  Economically inactive: Looking after home or family  \
0  Economically inactive: Looking after home or f...
1                                                112
2                                                548
3                                                144
4                                                206

   Economically inactive: Long-term sick or disabled  \
0  Economically inactive: Long-term sick or disabled
1                                                 47
2                                                281
3                                                 42
4                                                 82

   Economically inactive: Other
0  Economically inactive: Other
1                            68
2                           594
3                            83
4                           185
Age 20 to 21 tail
    local authority: district / unitary (prior to April 2015)  laua_code  \
344                                         Caerphilly         W06000018
345                                      Blaenau Gwent         W06000019
346                                            Torfaen         W06000020
347                                      Monmouthshire         W06000021
348                                            Newport         W06000022

    Economically active: In employment: Employee: Part-time (including full-time students)  \
344                                                873
345                                                396
346                                                563
347                                                385
348                                               1125

    Economically active: In employment: Employee: Full-time (including full-time students)  \
344                                               1552
345                                                582
346                                                854
347                                                681
348                                               1097

    Economically active: In employment: Self-employed: Part-time (including full-time students)  \
344                                                 25
345                                                  7
346                                                 11
347                                                 16
348                                                 25

    Economically active: In employment: Self-employed: Full-time (including full-time students)  \
344                                                 82
345                                                 35
346                                                 39
347                                                 46
348                                                 37

    Economically active: Unemployed (including full-time students)  \
344                                                750
345                                                386
346                                                380
347                                                222
348                                                674

    Economically inactive: Retired  \
344                              2
345                              5
346                              1
347                              0
348                              3

    Economically inactive: Student (including full-time students)  \
344                                                388
345                                                165
346                                                167
347                                                146
348                                                843

    Economically inactive: Looking after home or family  \
344                                                219
345                                                118
346                                                 96
347                                                 55
348                                                161

    Economically inactive: Long-term sick or disabled  \
344                                               111
345                                                46
346                                                64
347                                                31
348                                                81

    Economically inactive: Other
344                          147
345                           83
346                           67
347                           55
348                          139
Age 22 to 24
  local authority: district / unitary (prior to April 2015)  laua_code  \
0  local authority: district / unitary (prior to ...               NaN
1                                         Darlington         E06000005
2                                      County Durham         E06000047
3                                         Hartlepool         E06000001
4                                      Middlesbrough         E06000002

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0  Economically active: In employment: Employee: ...
1                                                737
2                                               3436
3                                                743
4                                               1411

  Economically active: In employment: Employee: Full-time (including full-time students)  \
0  Economically active: In employment: Employee: ...
1                                               1964
2                                               8623
3                                               1493
4                                               2213

  Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0  Economically active: In employment: Self-emplo...
1                                                 35
2                                                178
3                                                 33
4                                                 62

  Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0  Economically active: In employment: Self-emplo...
1                                                 81
2                                                427
3                                                 93
4                                                119

  Economically active: Unemployed (including full-time students)  \
0  Economically active: Unemployed (including ful...
1                                                451
2                                               1967
3                                                641
4                                               1106

   Economically inactive: Retired  \
0  Economically inactive: Retired
1                               1
2                              15
3                               2
4                               2

  Economically inactive: Student (including full-time students)  \
0  Economically inactive: Student (including full...
1                                                106
2                                               2185
3                                                132
4                                                980

  Economically inactive: Looking after home or family  \
0  Economically inactive: Looking after home or f...
1                                                198
2                                               1000
3                                                287
4                                                470

   Economically inactive: Long-term sick or disabled  \
0  Economically inactive: Long-term sick or disabled
1                                                 79
2                                                555
3                                                110
4                                                169

   Economically inactive: Other
0  Economically inactive: Other
1                           120
2                           628
3                           151
4                           264
Age 22 to 24 tail
    local authority: district / unitary (prior to April 2015)  laua_code  \
344                                         Caerphilly         W06000018
345                                      Blaenau Gwent         W06000019
346                                            Torfaen         W06000020
347                                      Monmouthshire         W06000021
348                                            Newport         W06000022

    Economically active: In employment: Employee: Part-time (including full-time students)  \
344                                               1182
345                                                498
346                                                653
347                                                486
348                                               1246

    Economically active: In employment: Employee: Full-time (including full-time students)  \
344                                               3325
345                                               1311
346                                               1653
347                                               1381
348                                               2593

    Economically active: In employment: Self-employed: Part-time (including full-time students)  \
344                                                 48
345                                                 15
346                                                 24
347                                                 33
348                                                 50

    Economically active: In employment: Self-employed: Full-time (including full-time students)  \
344                                                202

    local authority: district / unitary (prior to April 2015)  laua_code  \
344                                         Caerphilly         W06000018
345                                      Blaenau Gwent         W06000019
346                                            Torfaen         W06000020
347                                      Monmouthshire         W06000021
348                                            Newport         W06000022

    Economically active: In employment: Employee: Part-time (including full-time students)  \
344                                                713
345                                                283
346                                                424
347                                                700
348                                                763

    Economically active: In employment: Employee: Full-time (including full-time students)  \
344                                                600
345                                                255
346                                                363
347                                                499
348                                                535

    Economically active: In employment: Self-employed: Part-time (including full-time students)  \
344                                                204
345                                                 67
346                                                111
347                                                467
348                                                232

    Economically active: In employment: Self-employed: Full-time (including full-time students)  \
344                                                264
345                                                 77
346                                                135
347                                                589
348                                                274

    Economically active: Unemployed (including full-time students)  \
344                                                 41
345                                                 24
346                                                 20
347                                                 28
348                                                 39

    Economically inactive: Retired  \
344                          26078
345                          10971
346                          14577
347                          16156
348                          20946

    Economically inactive: Student (including full-time students)  \
344                                                 62
345                                                 33
346                                                 33
347                                                 28
348                                                 35

    Economically inactive: Looking after home or family  \
344                                                 85
345                                                 53
346                                                 63
347                                                 93
348                                                 91

    Economically inactive: Long-term sick or disabled  \
344                                               882
345                                               423
346                                               380
347                                               224
348                                               457

    Economically inactive: Other
344                          636
345                          291
346                          264
347                          259
348                          379

In [42]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].drop([0], inplace=True)
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].reset_index(inplace=True)

In [43]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].head())

Age 16 to 19
   index local authority: district / unitary (prior to April 2015)  laua_code  \
0      1                                         Darlington         E06000005
1      2                                      County Durham         E06000047
2      3                                         Hartlepool         E06000001
3      4                                      Middlesbrough         E06000002
4      5                                     Northumberland         E06000057

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0                                               1246
1                                               4930
2                                                884
3                                               1542
4                                               3388

  Economically active: In employment: Employee: Full-time (including full-time students)  \
0                                                619
1                                               3344
2                                                539
3                                                751
4                                               2130

  Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0                                                 27
1                                                 85
2                                                 12
3                                                 22
4                                                 37

  Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0                                                 16
1                                                 97
2                                                  8
3                                                 23
4                                                 81

  Economically active: Unemployed (including full-time students)  \
0                                                827
1                                               3854
2                                                915
3                                               1460
4                                               2037

  Economically inactive: Retired  \
0                              1
1                             12
2                              1
3                              1
4                             17

  Economically inactive: Student (including full-time students)  \
0                                               2109
1                                              13699
2                                               2382
3                                               4039
4                                               6363

  Economically inactive: Looking after home or family  \
0                                                 77
1                                                397
2                                                112
3                                                143
4                                                193

  Economically inactive: Long-term sick or disabled  \
0                                                36
1                                               214
2                                                31
3                                                52
4                                                83

  Economically inactive: Other
0                          120
1                          753
2                          137
3                          220
4                          294
Age 20 to 21
   index local authority: district / unitary (prior to April 2015)  laua_code  \
0      1                                         Darlington         E06000005
1      2                                      County Durham         E06000047
2      3                                         Hartlepool         E06000001
3      4                                      Middlesbrough         E06000002
4      5                                     Northumberland         E06000057

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0                                                624
1                                               3177
2                                                536
3                                               1223
4                                               1494

  Economically active: In employment: Employee: Full-time (including full-time students)  \
0                                                857
1                                               3903
2                                                667
3                                                907
4                                               2479

  Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0                                                 13
1                                                100
2                                                  9
3                                                 38
4                                                 55

  Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0                                                 22
1                                                169
2                                                 24
3                                                 42
4                                                126

  Economically active: Unemployed (including full-time students)  \
0                                                369
1                                               1808
2                                                541
3                                                927
4                                                914

  Economically inactive: Retired  \
0                              1
1                              9
2                              1
3                              4
4                              4

  Economically inactive: Student (including full-time students)  \
0                                                186
1                                               5552
2                                                223
3                                               1280
4                                                587

  Economically inactive: Looking after home or family  \
0                                                112
1                                                548
2                                                144
3                                                206
4                                                234

  Economically inactive: Long-term sick or disabled  \
0                                                47
1                                               281
2                                                42
3                                                82
4                                               137

  Economically inactive: Other
0                           68
1                          594
2                           83
3                          185
4                          209
Age 22 to 24
   index local authority: district / unitary (prior to April 2015)  laua_code  \
0      1                                         Darlington         E06000005
1      2                                      County Durham         E06000047
2      3                                         Hartlepool         E06000001
3      4                                      Middlesbrough         E06000002
4      5                                     Northumberland         E06000057

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0                                                737
1                                               3436
2                                                743
3                                               1411
4                                               1958

  Economically active: In employment: Employee: Full-time (including full-time students)  \
0                                               1964
1                                               8623
2                                               1493
3                                               2213
4                                               5097

  Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0                                                 35
1                                                178
2                                                 33
3                                                 62
4                                                 96

  Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0                                                 81
1                                                427
2                                                 93
3                                                119
4                                                262

  Economically active: Unemployed (including full-time students)  \
0                                                451
1                                               1967
2                                                641
3                                               1106
4                                               1114

  Economically inactive: Retired  \
0                              1
1                             15
2                              2
3                              2
4                              4

  Economically inactive: Student (including full-time students)  \
0                                                106
1                                               2185
2                                                132
3                                                980
4                                                358

  Economically inactive: Looking after home or family  \
0                                                198
1                                               1000
2                                                287
3                                                470
4                                                509

  Economically inactive: Long-term sick or disabled  \
0                                                79
1                                               555
2                                               110
3                                               169
4                                               231

  Economically inactive: Other
0                          120
1                          628
2                          151
3                          264
4                          356
Age 25 to 29
   index local authority: district / unitary (prior to April 2015)  laua_code  \
0      1                                         Darlington         E06000005
1      2                                      County Durham         E06000047
2      3                                         Hartlepool         E06000001
3      4                                      Middlesbrough         E06000002
4      5                                     Northumberland         E06000057

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0                                               1082
1                                               4790
2                                               1012
3                                               1741
4                                               2656

  Economically active: In employment: Employee: Full-time (including full-time students)  \
0                                               3747
1                                              17001
2                                               2650
3                                               4186
4                                               8826

  Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0                                                 96
1                                                433
2                                                 76
3                                                134
4                                                256

  Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0                                                226
1                                               1127
2                                                166
3                                                304
4                                                772

  Economically active: Unemployed (including full-time students)  \
0                                                585
1                                               2369
2                                                701
3                                               1205
4                                               1359

  Economically inactive: Retired  \
0                              3
1                             18
2                              4
3                              4
4                              7

  Economically inactive: Student (including full-time students)  \
0                                                112
1                                               1061
2                                                 96
3                                                515
4                                                254

  Economically inactive: Looking after home or family  \
0                                                426
1                                               1869
2                                                509
3                                                899
4                                               1046

  Economically inactive: Long-term sick or disabled  \
0                                               189
1                                              1162
2                                               215
3                                               353
4                                               526

  Economically inactive: Other
0                          141
1                          798
2                          193
3                          424
4                          485
Age 30 to 34
   index local authority: district / unitary (prior to April 2015)  laua_code  \
0      1                                         Darlington         E06000005
1      2                                      County Durham         E06000047
2      3                                         Hartlepool         E06000001
3      4                                      Middlesbrough         E06000002
4      5                                     Northumberland         E06000057

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0                                               1163
1                                               4885
2                                                946
3                                               1464
4                                               2991

  Economically active: In employment: Employee: Full-time (including full-time students)  \
0                                               3490
1                                              15460
2                                               2328
3                                               3461
4                                               8515

  Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0                                                128
1                                                531
2                                                 99
3                                                232
4                                                362

  Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0                                                331
1                                               1444
2                                                211
3                                                364
4                                               1096

  Economically active: Unemployed (including full-time students)  \
0                                                393
1                                               1644
2                                                568
3                                                882
4                                               1019

  Economically inactive: Retired  \
0                              5
1                             17
2                              5
3                              8
4                             17

  Economically inactive: Student (including full-time students)  \
0                                                 66
1                                                449
2                                                 55
3                                                261
4                                                137

  Economically inactive: Looking after home or family  \
0                                                460
1                                               1729
2                                                439
3                                                829
4                                               1062

  Economically inactive: Long-term sick or disabled  \
0                                               253
1                                              1293
2                                               257
3                                               456
4                                               565

  Economically inactive: Other
0                          140
1                          681
2                          125
3                          338
4                          357
Age 35 to 39
   index local authority: district / unitary (prior to April 2015)  laua_code  \
0      1                                         Darlington         E06000005
1      2                                      County Durham         E06000047
2      3                                         Hartlepool         E06000001
3      4                                      Middlesbrough         E06000002
4      5                                     Northumberland         E06000057

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0                                               1331
1                                               5628
2                                               1043
3                                               1690
4                                               3680

  Economically active: In employment: Employee: Full-time (including full-time students)  \
0                                               3516
1                                              16082
2                                               2510
3                                               3307
4                                               9003

  Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0                                                155
1                                                696
2                                                128
3                                                198
4                                                539

  Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0                                                450
1                                               2017
2                                                321
3                                                438

In [44]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].drop(['index'], axis=1, inplace=True)
    #check all dataframes are the same length
    print(len(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]))

348
348
348
348
348
348
348
348
348
348
348
348

In [45]:
test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21']

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other
0,Darlington,E06000005,624,857,13,22,369,1,186,112,47,68
1,County Durham,E06000047,3177,3903,100,169,1808,9,5552,548,281,594
2,Hartlepool,E06000001,536,667,9,24,541,1,223,144,42,83
3,Middlesbrough,E06000002,1223,907,38,42,927,4,1280,206,82,185
4,Northumberland,E06000057,1494,2479,55,126,914,4,587,234,137,209
...,...,...,...,...,...,...,...,...,...,...,...,...
343,Caerphilly,W06000018,873,1552,25,82,750,2,388,219,111,147
344,Blaenau Gwent,W06000019,396,582,7,35,386,5,165,118,46,83
345,Torfaen,W06000020,563,854,11,39,380,1,167,96,64,67
346,Monmouthshire,W06000021,385,681,16,46,222,0,146,55,31,55
347,Newport,W06000022,1125,1097,25,37,674,3,843,161,81,139

In [46]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].dtypes)

local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                                            object
Economically inactive: Long-term sick or disabled                                              object
Economically inactive: Other                                                                   object
dtype: object

Again the datatypes of the integer columns have to be changed

In [47]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    cols = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].columns
    #test_dfs['df_nomis_2023_08_06_172146.xlsx'][i][new_cols[2:-1]].astype(int)test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].convert_dtypes(convert)
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i] = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].convert_dtypes(convert_string=False)

In [48]:
#check again
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].dtypes)

local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object
local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                                             Int64
Economically inactive: Long-term sick or disabled                                               Int64
Economically inactive: Other                                                                    Int64
dtype: object

In [49]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].isna().sum())
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].describe())

local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64
       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         1806.979885
std                                          1165.415112
min                                                  6.0
25%                                               1132.5
50%                                               1534.0
75%                                              2080.25
max                                               9608.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                          900.433908
std                                           553.671751
min                                                 10.0
25%                                                570.0
50%                                                743.0
75%                                               1038.5
max                                               4151.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                           38.928161
std                                            27.379982
min                                                  1.0
25%                                                 21.0
50%                                                 33.0
75%                                                 49.0
max                                                226.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                           45.054598
std                                            28.426555
min                                                  0.0
25%                                                 26.0
50%                                                 37.0
75%                                                 55.0
max                                                224.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                         1117.836207
std                                          1009.530312
min                                                  2.0
25%                                                561.0
50%                                                797.5
75%                                              1406.75
max                                              10429.0

       Economically inactive: Retired  \
count                           348.0
mean                         3.551724
std                           3.36282
min                               0.0
25%                               1.0
50%                               3.0
75%                               5.0
max                              24.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                         3988.614943
std                                           3577.85392
min                                                  5.0
25%                                              1973.75
50%                                               2757.0
75%                                              4940.75
max                                              38548.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                           82.114943
std                                            77.157226
min                                                  0.0
25%                                                 37.0
50%                                                 59.0
75%                                                 98.5
max                                                784.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                            40.33908
std                                            35.256246
min                                                  1.0
25%                                                 19.0
50%                                                 30.0
75%                                                49.25
max                                                371.0

       Economically inactive: Other
count                         348.0
mean                     169.798851
std                      152.905689
min                             2.0
25%                            82.0
50%                           115.5
75%                           215.0
max                          1597.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64
       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                          986.471264
std                                          1059.978235
min                                                  5.0
25%                                                414.0
50%                                                614.0
75%                                              1211.75
max                                               8511.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                         1273.215517
std                                           786.821397
min                                                 20.0
25%                                                807.5
50%                                               1024.0
75%                                               1521.5
max                                               6672.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                           42.034483
std                                            38.631846
min                                                  0.0
25%                                                 20.0
50%                                                 28.0
75%                                                 47.0
max                                                295.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                            79.37931
std                                            50.981884
min                                                  1.0
25%                                                 47.0
50%                                                 64.0
75%                                                 95.0
max                                                344.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                          550.804598
std                                           623.215254
min                                                  0.0
25%                                                201.0
50%                                                333.0
75%                                               681.25
max                                               6319.0

       Economically inactive: Retired  \
count                           348.0
mean                         2.272989
std                          2.259189
min                               0.0
25%                               1.0
50%                               2.0
75%                               3.0
max                              16.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                         1139.204023
std                                          2162.701356
min                                                  5.0
25%                                                160.0
50%                                                275.5
75%                                              1007.75
max                                              15219.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                          131.821839
std                                            122.25658
min                                                  0.0
25%                                                 58.0
50%                                                 94.5
75%                                               165.25
max                                               1229.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                                59.5
std                                            53.005818
min                                                  0.0
25%                                                 27.0
50%                                                 44.0
75%                                                72.25
max                                                480.0

       Economically inactive: Other
count                         348.0
mean                      127.95977
std                      123.799287
min                             1.0
25%                            54.0
50%                            84.0
75%                           168.0
max                          1220.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64

       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         1125.798851
std                                          1095.174011
min                                                  4.0
25%                                                486.0
50%                                                711.0
75%                                               1403.5
max                                               9603.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                         3095.416667
std                                          2227.752831
min                                                 61.0
25%                                              1739.75
50%                                               2335.0
75%                                               3874.5
max                                              18760.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                           96.951149
std                                            99.821168
min                                                  0.0
25%                                                 43.0
50%                                                 60.0
75%                                                104.0
max                                                684.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                           217.87069
std                                           157.185395
min                                                  5.0
25%                                                122.0
50%                                                161.0
75%                                               254.25
max                                                988.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                          616.899425
std                                           671.401119
min                                                  1.0
25%                                                240.5
50%                                                376.0
75%                                               774.75
max                                               6990.0

       Economically inactive: Retired  \
count                           348.0
mean                         3.454023
std                          3.465043
min                               0.0
25%                               1.0
50%                               3.0
75%                               5.0
max                              34.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                          752.586207
std                                           1368.23519
min                                                  0.0
25%                                                110.0
50%                                                189.5
75%                                               656.75
max                                               9997.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                          310.663793
std                                           311.333534
min                                                  1.0
25%                                                133.0
50%                                                217.0
75%                                               385.25
max                                               3556.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                          119.192529
std                                           103.404108
min                                                  0.0
25%                                                56.75
50%                                                 88.0
75%                                                146.0
max                                                975.0

       Economically inactive: Other
count                         348.0
mean                     208.862069
std                      215.593995
min                             1.0
25%                            88.0
50%                           135.0
75%                          262.25
max                          2386.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64
       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         1498.103448
std                                          1375.055097
min                                                 12.0
25%                                                688.5
50%                                                997.5
75%                                               1845.0
max                                              12528.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                         6260.140805
std                                           5447.99193
min                                                 97.0
25%                                              2999.75
50%                                               4346.0
75%                                              7893.75
max                                              40385.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                          227.376437
std                                           250.099414
min                                                  3.0
25%                                                 96.0
50%                                                134.0
75%                                               249.25
max                                               1749.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                           595.95977
std                                           545.466808
min                                                 13.0
25%                                               289.75
50%                                                399.0
75%                                               667.25
max                                               3073.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                          748.928161
std                                           848.987427
min                                                  3.0
25%                                                265.5
50%                                                429.0
75%                                                949.5
max                                               8790.0

       Economically inactive: Retired  \
count                           348.0
mean                         5.456897
std                          5.221424
min                               0.0
25%                               2.0
50%                               4.0
75%                               7.0
max                              47.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                          433.836207
std                                           723.042901
min                                                  1.0
25%                                                81.25
50%                                                143.5
75%                                                400.5
max                                               5250.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                          692.227011
std                                           718.321906
min                                                  3.0
25%                                               286.75
50%                                                448.0
75%                                                865.0
max                                               7983.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                           247.95977
std                                            228.11111
min                                                  0.0
25%                                                108.0
50%                                                176.0
75%                                               321.25
max                                               2161.0

       Economically inactive: Other
count                         348.0
mean                         314.75
std                      371.161939
min                             3.0
25%                           111.0
50%                           174.0
75%                           367.5
max                          3928.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64

       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         1618.206897
std                                          1276.261269
min                                                 27.0
25%                                                891.0
50%                                               1133.5
75%                                              2032.75
max                                              12191.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                         5764.474138
std                                          4751.831285
min                                                 61.0
25%                                               2741.5
50%                                               4012.5
75%                                               7375.0
max                                              35486.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                          306.784483
std                                           306.653522
min                                                  4.0
25%                                                138.0
50%                                                195.0
75%                                               328.25
max                                               2381.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                          771.979885
std                                           701.955402
min                                                 27.0
25%                                                377.5
50%                                                509.0
75%                                               836.25
max                                               4149.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                          567.235632
std                                           648.875811
min                                                  2.0
25%                                                199.0
50%                                                328.5
75%                                               737.75
max                                               7087.0

       Economically inactive: Retired  \
count                           348.0
mean                         6.163793
std                          5.453937
min                               0.0
25%                               3.0
50%                               5.0
75%                               8.0
max                              40.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                          198.077586
std                                           296.698184
min                                                  1.0
25%                                                46.75
50%                                                 76.5
75%                                                208.5
max                                               2435.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                          783.051724
std                                           772.410406
min                                                  4.0
25%                                                358.0
50%                                                525.0
75%                                                988.5
max                                               8895.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                          302.060345
std                                           285.620391
min                                                  1.0
25%                                               129.75
50%                                                212.5
75%                                                389.0
max                                               2843.0

       Economically inactive: Other
count                         348.0
mean                     267.928161
std                      337.504425
min                             0.0
25%                           93.75
50%                           142.0
75%                          303.25
max                          3662.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64
       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         1911.028736
std                                          1298.707198
min                                                 27.0
25%                                              1128.75
50%                                               1503.5
75%                                               2311.0
max                                              12125.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                         5363.729885
std                                          3640.935392
min                                                 66.0
25%                                               2932.5
50%                                               4107.0
75%                                              6848.75
max                                              30022.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                          387.994253
std                                           320.783937
min                                                  4.0
25%                                               199.75
50%                                                284.5
75%                                               444.25
max                                               2762.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                          926.807471
std                                           675.543863
min                                                 28.0
25%                                               528.75
50%                                                670.5
75%                                               1061.5
max                                               4701.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                           525.62931
std                                            551.46269
min                                                  0.0
25%                                               211.75
50%                                                320.0
75%                                                685.0
max                                               6049.0

       Economically inactive: Retired  \
count                           348.0
mean                         8.738506
std                          7.600471
min                               0.0
25%                               4.0
50%                               7.0
75%                              10.0
max                              55.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                          127.281609
std                                           160.403529
min                                                  0.0
25%                                                39.75
50%                                                 61.0
75%                                               146.75
max                                               1388.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                           807.58046
std                                           691.993184
min                                                  3.0
25%                                               407.75
50%                                                581.5
75%                                               1058.5
max                                               7821.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                          425.071839
std                                           390.962955
min                                                  0.0
25%                                                187.5
50%                                                295.0
75%                                               540.25
max                                               3544.0

       Economically inactive: Other
count                         348.0
mean                     240.738506
std                       283.53445
min                             2.0
25%                            87.0
50%                           132.0
75%                           273.5
max                          2938.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64
       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         2165.195402
std                                           1378.76547
min                                                 33.0
25%                                               1375.5
50%                                               1762.0
75%                                              2552.75
max                                              12660.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                         5802.787356
std                                          3622.355966
min                                                 82.0
25%                                              3569.75
50%                                               4679.0
75%                                               7203.0
max                                              30842.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                          451.511494
std                                           316.097835
min                                                 10.0
25%                                               260.75
50%                                                357.5
75%                                               533.75
max                                               2832.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                         1165.795977
std                                           712.296652
min                                                 35.0
25%                                                722.0
50%                                                944.0
75%                                              1358.25
max                                               5335.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                          545.678161
std                                           532.885154
min                                                  1.0
25%                                               235.75
50%                                                341.0
75%                                                717.0
max                                               5641.0

       Economically inactive: Retired  \
count                           348.0
mean                        19.772989
std                         13.881452
min                               0.0
25%                              11.0
50%                              17.0
75%                              24.0
max                             129.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                           89.873563
std                                           102.960058
min                                                  0.0
25%                                                 34.0
50%                                                 52.0
75%                                                106.0
max                                                903.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                          707.833333
std                                           566.033905
min                                                  5.0
25%                                               370.25
50%                                                528.5
75%                                                865.0
max                                               6315.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                          595.698276
std                                           549.901876
min                                                  3.0
25%                                               255.75
50%                                                407.0
75%                                               754.75
max                                               4800.0

       Economically inactive: Other
count                         348.0
mean                     234.844828
std                      255.358919
min                             1.0
25%                            95.0
50%                           138.5
75%                           275.0
max                          2627.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64
       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         2057.224138
std                                          1263.720869
min                                                 14.0
25%                                              1323.25
50%                                               1715.5
75%                                              2400.75
max                                              11026.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                          5943.87069
std                                          3650.896141
min                                                 85.0
25%                                               3775.5
50%                                               4865.0
75%                                              7129.25
max                                              31411.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                          438.502874
std                                            285.03551
min                                                 13.0
25%                                                250.0

       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         1717.905172
std                                          1059.161214
min                                                 23.0
25%                                               1087.0
50%                                               1436.5
75%                                               1954.0
max                                               8674.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                         5046.885057
std                                          3076.830864
min                                                 66.0
25%                                              3245.75
50%                                               4134.0
75%                                               6047.5
max                                              26022.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                           382.12069
std                                           242.010485
min                                                  9.0
25%                                                229.0
50%                                                322.0
75%                                                459.5
max                                               1847.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                         1093.491379
std                                           635.199601
min                                                 46.0
25%                                                704.5
50%                                                949.5
75%                                              1260.25
max                                               5575.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                          407.281609
std                                           350.821039
min                                                  6.0
25%                                               199.75
50%                                                282.0
75%                                                526.0
max                                               3769.0

       Economically inactive: Retired  \
count                           348.0
mean                       194.221264
std                        127.751898
min                               2.0
25%                             119.0
50%                             165.0
75%                            220.25
max                             928.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                           27.988506
std                                            26.721639
min                                                  0.0
25%                                                12.75
50%                                                 20.0
75%                                                 32.0
max                                                215.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                          462.244253
std                                           330.493397
min                                                  1.0
25%                                                269.0
50%                                                374.0
75%                                                545.0
max                                               3564.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                          792.646552
std                                           745.134356
min                                                  1.0
25%                                               329.75
50%                                                547.5
75%                                                992.5
max                                               6343.0

       Economically inactive: Other
count                         348.0
mean                      224.91092
std                       206.18862
min                             1.0
25%                          107.75
50%                           147.5
75%                           261.5
max                          2147.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64
       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         1529.600575
std                                           925.963916
min                                                 24.0
25%                                                979.5
50%                                               1306.0
75%                                               1728.5
max                                               7279.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                         3761.422414
std                                          2234.971573
min                                                 43.0
25%                                              2480.75
50%                                               3122.5
75%                                              4474.25
max                                              19154.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                          368.155172
std                                           227.955502
min                                                 14.0
25%                                               227.75
50%                                                317.5
75%                                               443.25
max                                               2141.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                          881.939655
std                                           509.580982
min                                                 46.0
25%                                                579.0
50%                                                787.0
75%                                               1022.0
max                                               4868.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                          335.198276
std                                            271.06096
min                                                  0.0
25%                                                172.0
50%                                                244.5
75%                                                411.5
max                                               3008.0

       Economically inactive: Retired  \
count                           348.0
mean                       715.551724
std                        467.112598
min                               9.0
25%                            440.75
50%                             611.0
75%                             812.0
max                            3458.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                           15.902299
std                                            14.255256
min                                                  0.0
25%                                                  7.0
50%                                                 12.0
75%                                                 19.0
max                                                110.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                          425.571839
std                                           286.822467
min                                                  3.0
25%                                                252.5
50%                                                355.5
75%                                               499.25
max                                               3027.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                          889.560345
std                                           829.416582
min                                                  1.0
25%                                                369.5
50%                                                609.5
75%                                              1144.25
max                                               7159.0

       Economically inactive: Other
count                         348.0
mean                     226.278736
std                      197.673806
min                             2.0
25%                           115.0
50%                           158.0
75%                          266.25
max                          2197.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64
       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                          1342.37931
std                                           779.567126
min                                                 23.0
25%                                               889.25
50%                                               1183.5
75%                                              1550.25
max                                               5850.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                         2164.094828
std                                          1210.677072
min                                                 37.0
25%                                              1439.75
50%                                               1869.0
75%                                              2536.75
max                                              10165.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                          390.632184
std                                           239.632589
min                                                 15.0
25%                                                244.0
50%                                                340.0
75%                                               485.25
max                                               2421.0

       Economically active: In employment: Self-employed: Full-time (including full-time students)  \
count                                              348.0
mean                                          699.847701
std                                           414.857751
min                                                 45.0
25%                                                451.0
50%                                                626.0
75%                                                835.5
max                                               4316.0

       Economically active: Unemployed (including full-time students)  \
count                                              348.0
mean                                          176.764368
std                                            120.16253
min                                                  2.0
25%                                                106.0
50%                                                145.5
75%                                                215.0
max                                               1264.0

       Economically inactive: Retired  \
count                           348.0
mean                      4089.632184
std                       2584.226051
min                              41.0
25%                            2592.5
50%                            3477.0
75%                            4596.5
max                           19644.0

       Economically inactive: Student (including full-time students)  \
count                                              348.0
mean                                           15.497126
std                                            12.020036
min                                                  1.0
25%                                                  8.0
50%                                                 12.0
75%                                                 19.0
max                                                 96.0

       Economically inactive: Looking after home or family  \
count                                              348.0
mean                                          113.445402
std                                            83.045211
min                                                  2.0
25%                                                 65.0
50%                                                 90.0
75%                                               131.25
max                                                844.0

       Economically inactive: Long-term sick or disabled  \
count                                              348.0
mean                                          548.244253
std                                           503.159774
min                                                  0.0
25%                                                235.5
50%                                                385.0
75%                                                658.0
max                                               3669.0

       Economically inactive: Other
count                         348.0
mean                     163.951149
std                      133.004216
min                             6.0
25%                            83.0
50%                           120.0
75%                           196.5
max                          1460.0
local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
dtype: int64
       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0
mean                                         1072.511494
std                                           599.620709
min                                                 39.0
25%                                                709.0
50%                                                965.0
75%                                               1250.5
max                                               5050.0

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                                              348.0
mean                                          692.474138
std                                           400.832163
min                                                 22.0
25%                                               440.75
50%                                                595.0
75%                                               817.75
max                                               3583.0

       Economically active: In employment: Self-employed: Part-time (including full-time students)  \
count                                              348.0
mean                                           466.33046
std                                           311.422297
min                                                 36.0
25%                                               261.75

**This is where the cleaning will be slightly different, there are more categories of employment activity to take into account, however I want to get the same four columns added; total residents, total active, total inactive and total employed.  I also have to combine age groups as there are more age bands in the 2011 data so I will leave adding the age group to the dataframe until this is done.**

In [50]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    cols = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].columns[2:]   
    total = []
    active = []
    inactive = []
    employed = []
    for index, row in test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].iterrows():
        total.append(row[cols].sum())
        active.append(row[cols[:5]].sum())
        inactive.append(row[cols[5:]].sum())
        employed.append(row[cols[:4]].sum()) # the cols[2] here was initially cols[3] but that was incorrect 
    
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Total Residents'] = total
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Total Active'] = active
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Total Inactive'] = inactive
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Total Employed'] = employed

In [51]:
#check new columns in place
test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21']

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,624,857,13,22,369,1,186,112,47,68,2299,1885,414,1516
1,County Durham,E06000047,3177,3903,100,169,1808,9,5552,548,281,594,16141,9157,6984,7349
2,Hartlepool,E06000001,536,667,9,24,541,1,223,144,42,83,2270,1777,493,1236
3,Middlesbrough,E06000002,1223,907,38,42,927,4,1280,206,82,185,4894,3137,1757,2210
4,Northumberland,E06000057,1494,2479,55,126,914,4,587,234,137,209,6239,5068,1171,4154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,Caerphilly,W06000018,873,1552,25,82,750,2,388,219,111,147,4149,3282,867,2532
344,Blaenau Gwent,W06000019,396,582,7,35,386,5,165,118,46,83,1823,1406,417,1020
345,Torfaen,W06000020,563,854,11,39,380,1,167,96,64,67,2242,1847,395,1467
346,Monmouthshire,W06000021,385,681,16,46,222,0,146,55,31,55,1637,1350,287,1128
347,Newport,W06000022,1125,1097,25,37,674,3,843,161,81,139,4185,2958,1227,2284

Now I'll check all the calculations are correct by adding up the relevant figures in one row as before

In [52]:
print(624+857+13+22+369+1+186+112+47+68) #should equal 2299
print(624+857+13+22+369) #should equal 1885
print(1+186+112+47+68) #should equal 414
print(624+857+13+22) #should equal 1516

2299
1885
414
1516

Okay I'm happy with the results above.  I will now combine the age groups to match the 2021 data

In [53]:
test_dfs['df_nomis_2023_08_06_174635.xlsx'].keys()

dict_keys(['Age 16 to 19', 'Age 20 to 21', 'Age 22 to 24', 'Age 25 to 29', 'Age 30 to 34', 'Age 35 to 39', 'Age 40 to 44', 'Age 45 to 49', 'Age 50 to 54', 'Age 55 to 59', 'Age 60 to 64', 'Age 65 and over'])

In [54]:
test_dfs['df_nomis_2023_08_06_172146.xlsx'].keys()

dict_keys(['Aged 15 years and under', 'Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])

Right I will attempt to combine the three 16 to 24 age bands and store it in a new dictionary

In [55]:
test_dfs_2011_agecombined = {}

test_dfs_2011_agecombined['Aged 16 to 24 years'] = pd.concat([
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 16 to 19'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 22 to 24']
    ]
)
test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years'])

In [56]:
#checked the number of rows, should be 1044 (348 * 3)
test_dfs_2011_agecombined['Aged 16 to 24 years']

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1246,619,27,16,827,1,2109,77,36,120,5078,2735,2343,1908
1,County Durham,E06000047,4930,3344,85,97,3854,12,13699,397,214,753,27385,12310,15075,8456
2,Hartlepool,E06000001,884,539,12,8,915,1,2382,112,31,137,5021,2358,2663,1443
3,Middlesbrough,E06000002,1542,751,22,23,1460,1,4039,143,52,220,8253,3798,4455,2338
4,Northumberland,E06000057,3388,2130,37,81,2037,17,6363,193,83,294,14623,7673,6950,5636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,Caerphilly,W06000018,1182,3325,48,202,809,5,282,421,213,184,6671,5566,1105,4757
344,Blaenau Gwent,W06000019,498,1311,15,63,406,4,78,193,117,128,2813,2293,520,1887
345,Torfaen,W06000020,653,1653,24,73,364,2,122,234,129,92,3346,2767,579,2403
346,Monmouthshire,W06000021,486,1381,33,111,227,2,136,126,70,102,2674,2238,436,2011
347,Newport,W06000022,1246,2593,50,126,714,3,457,328,119,220,5856,4729,1127,4015

Okay I'm happy that the resultant frame has the correct number of rows, I will now attempt to combine the data for each area, I'll first take note of the total Residents figure for one area so that I can check the figures have been combined correctly

In [57]:
test_dfs_2011_agecombined['Aged 16 to 24 years'].loc[test_dfs_2011_agecombined['Aged 16 to 24 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1246,619,27,16,827,1,2109,77,36,120,5078,2735,2343,1908
0,Darlington,E06000005,624,857,13,22,369,1,186,112,47,68,2299,1885,414,1516
0,Darlington,E06000005,737,1964,35,81,451,1,106,198,79,120,3772,3268,504,2817

Above shows three entries for Darlington as expected with total resident figures of 5078, 2299 and 3772

In [58]:
cols = test_dfs_2011_agecombined['Aged 16 to 24 years'].columns[2:]
test_dfs_2011_agecombined['Aged 16 to 24 years'] = test_dfs_2011_agecombined['Aged 16 to 24 years'].groupby([
    'local authority: district / unitary (prior to April 2015)', 'laua_code'
])[cols].sum().reset_index()

In [59]:
test_dfs_2011_agecombined['Aged 16 to 24 years']

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Adur,E07000223,1357,1839,66,168,643,4,1265,187,88,122,5739,4073,1666,3430
1,Allerdale,E07000026,2240,3279,48,161,1036,11,1924,209,147,175,9230,6764,2466,5728
2,Amber Valley,E07000032,2454,4287,119,250,1453,5,2754,327,131,283,12063,8563,3500,7110
3,Arun,E07000224,3356,4601,158,350,1500,11,2930,376,194,314,13790,9965,3825,8465
4,Ashfield,E07000170,2522,4450,67,221,1829,9,2638,503,251,377,12867,9089,3778,7260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,Wychavon,E07000238,2466,3677,121,251,961,13,2534,250,108,237,10618,7476,3142,6515
344,Wycombe,E07000007,4128,5784,210,391,1884,11,5665,391,134,434,19032,12397,6635,10513
345,Wyre,E07000128,2659,3326,104,219,1129,9,2664,226,148,182,10666,7437,3229,6308
346,Wyre Forest,E07000239,2215,2937,81,211,1215,5,2137,339,130,264,9534,6659,2875,5444
347,York,E06000014,7800,7027,260,306,2873,2,12523,440,147,426,31804,18266,13538,15393

Okay the above seems to have the correct number of rows however the districts are now in alphabetical order.  I'll look for the darlington row and see if the total residents figure is as expected, i'll also check there are 348 distinct districts

In [60]:
print(len(set(test_dfs_2011_agecombined['Aged 16 to 24 years']['local authority: district / unitary (prior to April 2015)'])))

test_dfs_2011_agecombined['Aged 16 to 24 years'].loc[test_dfs_2011_agecombined['Aged 16 to 24 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

348

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
79,Darlington,E06000005,2607,3440,75,119,1647,3,2401,387,162,308,11149,7888,3261,6241

In [61]:
5078 +2299 + 3772 #should come to 11149 as shown above

11149

I'll now repeat the above steps with the other age groups

In [62]:
#step 1 create new combined df
test_dfs_2011_agecombined['Aged 25 to 34 years'] = pd.concat([
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 25 to 29'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 30 to 34']
    ]
)

test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years'])

In [63]:
#step 2 check the correct number of rows are present and note total residents numbers
test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1082,3747,96,226,585,3,112,426,189,141,6607,5736,871,5151
0,Darlington,E06000005,1163,3490,128,331,393,5,66,460,253,140,6429,5505,924,5112

In [64]:
#step 3 groupby authority and laua code
test_dfs_2011_agecombined['Aged 25 to 34 years'] = test_dfs_2011_agecombined['Aged 25 to 34 years'].groupby([
    'local authority: district / unitary (prior to April 2015)', 'laua_code'
])[cols].sum().reset_index()

In [65]:
#step4 check the result
print(len(set(test_dfs_2011_agecombined['Aged 25 to 34 years']['local authority: district / unitary (prior to April 2015)'])))

test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

348

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
79,Darlington,E06000005,2245,7237,224,557,978,8,178,886,442,281,13036,11241,1795,10263

In [66]:
6607+6429 #should be 13036

13036

In [67]:
#step 1 create new combined df
test_dfs_2011_agecombined['Aged 35 to 49 years'] = pd.concat([
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 35 to 39'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 40 to 44'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 45 to 49']
    ]
)

test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years'])

In [68]:
#step 2 check the correct number of rows are present and note total residents numbers
test_dfs_2011_agecombined['Aged 35 to 49 years'].loc[test_dfs_2011_agecombined['Aged 35 to 49 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1331,3516,155,450,389,10,51,457,362,126,6847,5841,1006,5452
0,Darlington,E06000005,1456,4014,222,609,405,18,39,335,422,121,7641,6706,935,6301
0,Darlington,E06000005,1415,4366,192,664,285,28,29,341,552,122,7994,6922,1072,6637

In [69]:
#step 3 groupby authority and laua code
test_dfs_2011_agecombined['Aged 35 to 49 years'] = test_dfs_2011_agecombined['Aged 35 to 49 years'].groupby([
    'local authority: district / unitary (prior to April 2015)', 'laua_code'
])[cols].sum().reset_index()

In [70]:
#step4 check the result
print(len(set(test_dfs_2011_agecombined['Aged 35 to 49 years']['local authority: district / unitary (prior to April 2015)'])))

test_dfs_2011_agecombined['Aged 35 to 49 years'].loc[test_dfs_2011_agecombined['Aged 35 to 49 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

348

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
79,Darlington,E06000005,4202,11896,569,1723,1079,56,119,1133,1336,369,22482,19469,3013,18390

In [71]:
6847 + 7641 + 7994 # should equal 22482

22482

In [72]:
#step 1 create new combined df
test_dfs_2011_agecombined['Aged 50 to 64 years'] = pd.concat([
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 50 to 54'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 55 to 59'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 60 to 64']
    ]
)

test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years'])

In [73]:
#step 2 check the correct number of rows are present and note total residents numbers
test_dfs_2011_agecombined['Aged 50 to 64 years'].loc[test_dfs_2011_agecombined['Aged 50 to 64 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1246,3695,165,646,315,150,19,287,599,136,7258,6067,1191,5752
0,Darlington,E06000005,1086,2645,177,475,276,559,8,284,682,116,6308,4659,1649,4383
0,Darlington,E06000005,908,1395,182,395,106,3092,4,77,406,120,6685,2986,3699,2880

In [74]:
#step 3 groupby authority and laua code
test_dfs_2011_agecombined['Aged 50 to 64 years'] = test_dfs_2011_agecombined['Aged 50 to 64 years'].groupby([
    'local authority: district / unitary (prior to April 2015)', 'laua_code'
])[cols].sum().reset_index()

In [75]:
#step4 check the result
print(len(set(test_dfs_2011_agecombined['Aged 50 to 64 years']['local authority: district / unitary (prior to April 2015)'])))

test_dfs_2011_agecombined['Aged 50 to 64 years'].loc[test_dfs_2011_agecombined['Aged 50 to 64 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

348

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
79,Darlington,E06000005,3240,7735,524,1516,697,3801,31,648,1687,372,20251,13712,6539,13015

In [76]:
7258+6308+6685==20251

True

In [77]:
#finally
test_dfs_2011_agecombined['Aged 65 years and over'] = test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 65 and over']
test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])

In [78]:
b = test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21']['local authority: district / unitary (prior to April 2015)'].tolist()

# combining the districts

The data from 2011 features rows pertaining to local authorities which have been amalgamated by 2022.  The data from the 2021 census defines the local authority as correct at 2022 although the figures are from 2021.  I will check first which areas are unique to the data from both years and see if I can ascertain which districts must be combined.

As there is 348 rows in each 2011 age band and 331 rows in each 2021 age band I will expect there to be 331 in the 2011 data when the changes have been identified and applied

In [79]:
districts_2021 = test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years']['2022 local authorities: district'].tolist()

In [80]:
districts_2011 = test_dfs_2011_agecombined['Aged 25 to 34 years']['local authority: district / unitary (prior to April 2015)'].tolist()

In [81]:
set(districts_2011).difference(set(districts_2021))

{'Aylesbury Vale',
 'Bournemouth',
 'Chiltern',
 'Christchurch',
 'Corby',
 'Daventry',
 'East Dorset',
 'East Northamptonshire',
 'Forest Heath',
 'Kettering',
 'North Dorset',
 'Northampton',
 'Poole',
 'Purbeck',
 'South Bucks',
 'South Northamptonshire',
 'St Edmundsbury',
 'Suffolk Coastal',
 'Taunton Deane',
 'Waveney',
 'Wellingborough',
 'West Dorset',
 'West Somerset',
 'Weymouth and Portland',
 'Wycombe'}

In [82]:
set(districts_2021).difference(set(districts_2011))

{'Bournemouth, Christchurch and Poole',
 'Buckinghamshire',
 'Dorset',
 'East Suffolk',
 'North Northamptonshire',
 'Somerset West and Taunton',
 'West Northamptonshire',
 'West Suffolk'}

The two cells above show the old authorities and their amalgamated counterparts respectively.  Having investigated the 8 council areas in the 2021 data I can see that the 25 areas in the 2011 data shown above do indeed make up these 8 areas.  I will now attempt to make the necessary changes.

In [83]:
#first I'm going to rename the district column to a simpler column header.  Shouldve done this earlier actually.
#im using the same column identifier as the fixed broadband data although I may change this later
for i in test_dfs_2011_agecombined:
    test_dfs_2011_agecombined[i].rename(columns={'local authority: district / unitary (prior to April 2015)': 'laua_name'}, 
                                        inplace=True)
test_dfs_2011_agecombined['Aged 25 to 34 years']

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Adur,E07000223,1065,3589,184,521,278,2,80,494,159,122,6494,5637,857,5359
1,Allerdale,E07000026,1794,5380,175,582,551,10,91,512,327,152,9574,8482,1092,7931
2,Amber Valley,E07000032,1953,7560,273,813,740,6,160,848,393,242,12988,11339,1649,10599
3,Arun,E07000224,2324,8206,337,1038,653,14,170,1003,383,376,14504,12558,1946,11905
4,Ashfield,E07000170,2240,7908,281,691,967,7,156,1141,503,320,14214,12087,2127,11120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,Wychavon,E07000238,1645,6456,274,724,529,9,154,583,232,217,10823,9628,1195,9099
344,Wycombe,E07000007,2692,13182,647,1481,923,18,390,1603,298,508,21742,18925,2817,18002
345,Wyre,E07000128,1728,5184,261,775,542,11,167,519,321,155,9663,8490,1173,7948
346,Wyre Forest,E07000239,1640,5838,228,645,629,8,122,669,350,213,10342,8980,1362,8351
347,York,E06000014,4186,16254,538,1350,1123,9,1366,1051,410,424,26711,23451,3260,22328

Using wikipedia I have managed to ascertain which locations unique to the 2011 dataset make up the unique locations of the 2021 dataset.  I have stored them in a dictionary below. NOTE** St Edmundsbury likely refers instead to bury st.edmunds, the former being the name of the cathedral located in the latter.  I will leave this as is just now but may have to change this later

In [84]:
district_change_dict = {
    'Bournemouth, Christchurch and Poole': ['Bournemouth', 'Christchurch', 'Poole'],
    'Buckinghamshire': ['South Bucks',  'Chiltern', 'Wycombe', 'Aylesbury Vale'],
    'Dorset': ['Weymouth and Portland', 'West Dorset', 'North Dorset', 'Purbeck', 'East Dorset'],
    'East Suffolk': ['Suffolk Coastal', 'Waveney'],
    'North Northamptonshire': ['Corby', 'East Northamptonshire', 'Kettering', 'Wellingborough'],
    'Somerset West and Taunton': ['Taunton Deane', 'West Somerset'],
    'West Northamptonshire': ['Daventry', 'Northampton', 'South Northamptonshire'],
    'West Suffolk': ['Forest Heath', 'St Edmundsbury']
    
    
}

I will also require the laua codes for the new districts which I will get below

In [85]:
temp = test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years'].loc[test_dfs['df_nomis_2023_08_06_172146.xlsx']
                    ['Aged 16 to 24 years']['2022 local authorities: district'].isin(['Bournemouth, Christchurch and Poole',
 'Buckinghamshire',
 'Dorset',
 'East Suffolk',
 'North Northamptonshire',
 'Somerset West and Taunton',
 'West Northamptonshire',
 'West Suffolk'])]
temp= temp.sort_values(by='2022 local authorities: district' )
temp

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed
289,"Bournemouth, Christchurch and Poole",E06000058,14769,1901,5193,2429,2729,18308,Aged 16 to 24 years,45329,24292,21037,19962
227,Buckinghamshire,E06000060,20336,2390,4546,1527,3324,17497,Aged 16 to 24 years,49620,28799,20821,24882
290,Dorset,E06000059,13766,1391,2982,956,2504,8686,Aged 16 to 24 years,30285,19095,11190,16748
180,East Suffolk,E07000244,9256,1145,1737,720,1823,5649,Aged 16 to 24 years,20330,12858,7472,10993
76,North Northamptonshire,E06000061,15577,1683,2987,1202,2754,8907,Aged 16 to 24 years,33110,21449,11661,18564
308,Somerset West and Taunton,E07000246,6297,627,1191,409,1008,3701,Aged 16 to 24 years,13233,8524,4709,7488
77,West Northamptonshire,E06000062,18217,2006,4767,1922,2956,13119,Aged 16 to 24 years,42987,26912,16075,22984
181,West Suffolk,E07000245,9455,749,1420,413,1541,3900,Aged 16 to 24 years,17478,12037,5441,10875

In [86]:
district_codes = temp['laua_code'].tolist()
district_codes

['E06000058',
 'E06000060',
 'E06000059',
 'E07000244',
 'E06000061',
 'E07000246',
 'E06000062',
 'E07000245']

In [87]:
district_change_dict

{'Bournemouth, Christchurch and Poole': ['Bournemouth',
  'Christchurch',
  'Poole'],
 'Buckinghamshire': ['South Bucks', 'Chiltern', 'Wycombe', 'Aylesbury Vale'],
 'Dorset': ['Weymouth and Portland',
  'West Dorset',
  'North Dorset',
  'Purbeck',
  'East Dorset'],
 'East Suffolk': ['Suffolk Coastal', 'Waveney'],
 'North Northamptonshire': ['Corby',
  'East Northamptonshire',
  'Kettering',
  'Wellingborough'],
 'Somerset West and Taunton': ['Taunton Deane', 'West Somerset'],
 'West Northamptonshire': ['Daventry',
  'Northampton',
  'South Northamptonshire'],
 'West Suffolk': ['Forest Heath', 'St Edmundsbury']}

Im happy I've got the codes and the district changes I will now try to complete the changes.  Firstly I will get a note of two of the groups of districts' information to ensure the changes are correctly implemented

In [88]:
west_suff_df = test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                                   ['laua_name'].isin(['Forest Heath', 'St Edmundsbury'])]
borne_df = test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                                   ['laua_name'].isin(['Bournemouth',
  'Christchurch',
  'Poole'])]
west_suff_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
111,Forest Heath,E07000201,1134,6522,170,488,355,1,122,763,154,373,10082,8669,1413,8314
272,St Edmundsbury,E07000204,2021,8454,294,769,524,5,150,742,259,541,13759,12062,1697,11538

In [89]:
borne_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
26,Bournemouth,E06000028,4170,17066,678,1963,1362,19,1093,1525,745,623,29244,25239,4005,23877
65,Christchurch,E07000048,642,2174,100,298,201,6,59,259,104,55,3898,3415,483,3214
216,Poole,E06000029,2584,10458,423,1105,721,8,290,1199,433,326,17547,15291,2256,14570

In [90]:
#bournemouth, christchurch and poole residents number 25-34
29244+3898+17547

50689

In [91]:
#west suffolk total residents 25-34
10082+ 13759

23841

**The four cells above show that this is a correct implementation of the changes required, I will now complete the changes for all 8 districts.**

In [92]:
cols = test_dfs_2011_agecombined[i].columns
for i in test_dfs_2011_agecombined:
    index= 0
    cols = test_dfs_2011_agecombined[i].columns
    for j in district_change_dict:
        tmp_df = test_dfs_2011_agecombined[i].loc[test_dfs_2011_agecombined[i]['laua_name'].isin(district_change_dict[j])].copy()
        tmp_df['laua_code'] = district_codes[index]
        tmp_df['laua_name'] = j
        tmp_df = tmp_df.groupby(['laua_name', 'laua_code'])[cols[2:]].sum().reset_index()
        print(j)
        print(district_codes[index])
        test_dfs_2011_agecombined[i] = pd.concat([test_dfs_2011_agecombined[i], tmp_df])
        index+=1

Bournemouth, Christchurch and Poole
E06000058
Buckinghamshire
E06000060
Dorset
E06000059
East Suffolk
E07000244
North Northamptonshire
E06000061
Somerset West and Taunton
E07000246
West Northamptonshire
E06000062
West Suffolk
E07000245
Bournemouth, Christchurch and Poole
E06000058
Buckinghamshire
E06000060
Dorset
E06000059
East Suffolk
E07000244
North Northamptonshire
E06000061
Somerset West and Taunton
E07000246
West Northamptonshire
E06000062
West Suffolk
E07000245
Bournemouth, Christchurch and Poole
E06000058
Buckinghamshire
E06000060
Dorset
E06000059
East Suffolk
E07000244
North Northamptonshire
E06000061
Somerset West and Taunton
E07000246
West Northamptonshire
E06000062
West Suffolk
E07000245
Bournemouth, Christchurch and Poole
E06000058
Buckinghamshire
E06000060
Dorset
E06000059
East Suffolk
E07000244
North Northamptonshire
E06000061
Somerset West and Taunton
E07000246
West Northamptonshire
E06000062
West Suffolk
E07000245
Bournemouth, Christchurch and Poole
E06000058
Buckinghamshire
E06000060
Dorset
E06000059
East Suffolk
E07000244
North Northamptonshire
E06000061
Somerset West and Taunton
E07000246
West Northamptonshire
E06000062
West Suffolk
E07000245

In [93]:
for i in test_dfs_2011_agecombined:
    print(len(test_dfs_2011_agecombined[i]))

356
356
356
356
356

In [94]:
print(test_dfs_2011_agecombined.keys())

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])

The above shows there is now 356 rows in the 2011 dataframes, 8 more than before meaning all 8 combined districts have now been added.  I will now drop the rows pertaining to the old districts which should leave 331 rows as with the 2021 data.  I will also check Bournemouth and west suffolk to see if the figures have been added correctly.

In [95]:
drop_list = ['Aylesbury Vale',
 'Bournemouth',
 'Chiltern',
 'Christchurch',
 'Corby',
 'Daventry',
 'East Dorset',
 'East Northamptonshire',
 'Forest Heath',
 'Kettering',
 'North Dorset',
 'Northampton',
 'Poole',
 'Purbeck',
 'South Bucks',
 'South Northamptonshire',
 'St Edmundsbury',
 'Suffolk Coastal',
 'Taunton Deane',
 'Waveney',
 'Wellingborough',
 'West Dorset',
 'West Somerset',
 'Weymouth and Portland',
 'Wycombe']

In [96]:
for i in test_dfs_2011_agecombined:
    test_dfs_2011_agecombined[i].drop(test_dfs_2011_agecombined[i].loc[test_dfs_2011_agecombined[i]
                                ['laua_name'].isin(drop_list)].index, inplace=True)
    print(len(test_dfs_2011_agecombined[i]))

331
331
331
331
331

In [97]:
check_df = test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                                   ['laua_name'].isin(['Bournemouth, Christchurch and Poole',
                                                                                 'West Suffolk'])]
check_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,"Bournemouth, Christchurch and Poole",E06000058,7396,29698,1201,3366,2284,33,1442,2983,1282,1004,50689,43945,6744,41661
0,West Suffolk,E07000245,3155,14976,464,1257,879,6,272,1505,413,914,23841,20731,3110,19852

The above shows the total residents figures are 50689 and 23841 respectively which was the expected result.  I am happy that the figures are correct and that the data for each data set is comparable directly by area.  I will now finish off by adding the year and age band to the 2011 dataframes, combining them before changing the 'laua' to uppercase and performing final checks on the data.

In [98]:
#add the age group and year
for i in test_dfs_2011_agecombined:
    test_dfs_2011_agecombined[i]['Age Group'] = i
    test_dfs_2011_agecombined[i]['Year'] = 2011

In [99]:
test_dfs_2011_agecombined.keys()

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])

In [100]:
test_dfs_2011_agecombined['Aged 25 to 34 years']

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed,Age Group,Year
0,Adur,E07000223,1065,3589,184,521,278,2,80,494,159,122,6494,5637,857,5359,Aged 25 to 34 years,2011
1,Allerdale,E07000026,1794,5380,175,582,551,10,91,512,327,152,9574,8482,1092,7931,Aged 25 to 34 years,2011
2,Amber Valley,E07000032,1953,7560,273,813,740,6,160,848,393,242,12988,11339,1649,10599,Aged 25 to 34 years,2011
3,Arun,E07000224,2324,8206,337,1038,653,14,170,1003,383,376,14504,12558,1946,11905,Aged 25 to 34 years,2011
4,Ashfield,E07000170,2240,7908,281,691,967,7,156,1141,503,320,14214,12087,2127,11120,Aged 25 to 34 years,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,East Suffolk,E07000244,3823,11555,539,1343,1190,16,204,1723,619,635,21647,18450,3197,17260,Aged 25 to 34 years,2011
0,North Northamptonshire,E06000061,5844,23148,763,2104,2156,17,385,2888,963,822,39090,34015,5075,31859,Aged 25 to 34 years,2011
0,Somerset West and Taunton,E07000246,2414,8555,344,1038,570,6,196,880,496,246,14745,12921,1824,12351,Aged 25 to 34 years,2011
0,West Northamptonshire,E06000062,6916,29027,1019,3080,2520,16,904,2887,943,1248,48560,42562,5998,40042,Aged 25 to 34 years,2011
0,West Suffolk,E07000245,3155,14976,464,1257,879,6,272,1505,413,914,23841,20731,3110,19852,Aged 25 to 34 years,2011

In [101]:
combined_2011_df = test_dfs_2011_agecombined['Aged 16 to 24 years']
for i in test_dfs_2011_agecombined:
    if i != 'Aged 16 to 24 years':
        combined_2011_df = pd.concat([test_dfs_2011_agecombined[i], combined_2011_df])
combined_2011_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed,Age Group,Year
0,Darlington,E06000005,550,343,200,213,36,16612,19,44,192,230,18439,1342,17097,1306,Aged 65 years and over,2011
1,County Durham,E06000047,2239,1731,828,1081,105,82939,129,212,1517,1564,92345,5984,86361,5879,Aged 65 years and over,2011
2,Hartlepool,E06000001,336,291,90,102,25,14071,33,22,290,338,15598,844,14754,819,Aged 65 years and over,2011
3,Middlesbrough,E06000002,550,377,137,125,47,18446,42,56,456,455,20691,1236,19455,1189,Aged 65 years and over,2011
4,Northumberland,E06000057,1929,1250,1004,1181,95,56092,76,195,646,836,63304,5459,57845,5364,Aged 65 years and over,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,East Suffolk,E07000244,5307,7151,222,455,2735,13,4879,679,275,669,22385,15870,6515,13135,Aged 16 to 24 years,2011
0,North Northamptonshire,E06000061,6734,11394,213,627,3900,18,7091,1094,411,815,32297,22868,9429,18968,Aged 16 to 24 years,2011
0,Somerset West and Taunton,E07000246,3513,5296,134,343,1335,10,3454,409,190,361,15045,10621,4424,9286,Aged 16 to 24 years,2011
0,West Northamptonshire,E06000062,8859,13928,322,836,4538,20,10181,1047,429,1102,41262,28483,12779,23945,Aged 16 to 24 years,2011
0,West Suffolk,E07000245,3666,8157,176,365,1683,15,3233,540,176,667,18678,14047,4631,12364,Aged 16 to 24 years,2011

In [102]:
#The +331 is to account for the lowest age band in the 2021 data which is not present in the 2011 data
#This 15 and under age band contains no values > 0 so it may be unnecceassary to keep it in but I'm keeping it for now
len(combined_2021_df) == (len(combined_2011_df) + 331)

True

In [103]:
combined_2011_df['laua_name'] = combined_2011_df['laua_name'].str.upper()

In [104]:
combined_2011_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed,Age Group,Year
0,DARLINGTON,E06000005,550,343,200,213,36,16612,19,44,192,230,18439,1342,17097,1306,Aged 65 years and over,2011
1,COUNTY DURHAM,E06000047,2239,1731,828,1081,105,82939,129,212,1517,1564,92345,5984,86361,5879,Aged 65 years and over,2011
2,HARTLEPOOL,E06000001,336,291,90,102,25,14071,33,22,290,338,15598,844,14754,819,Aged 65 years and over,2011
3,MIDDLESBROUGH,E06000002,550,377,137,125,47,18446,42,56,456,455,20691,1236,19455,1189,Aged 65 years and over,2011
4,NORTHUMBERLAND,E06000057,1929,1250,1004,1181,95,56092,76,195,646,836,63304,5459,57845,5364,Aged 65 years and over,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,EAST SUFFOLK,E07000244,5307,7151,222,455,2735,13,4879,679,275,669,22385,15870,6515,13135,Aged 16 to 24 years,2011
0,NORTH NORTHAMPTONSHIRE,E06000061,6734,11394,213,627,3900,18,7091,1094,411,815,32297,22868,9429,18968,Aged 16 to 24 years,2011
0,SOMERSET WEST AND TAUNTON,E07000246,3513,5296,134,343,1335,10,3454,409,190,361,15045,10621,4424,9286,Aged 16 to 24 years,2011
0,WEST NORTHAMPTONSHIRE,E06000062,8859,13928,322,836,4538,20,10181,1047,429,1102,41262,28483,12779,23945,Aged 16 to 24 years,2011
0,WEST SUFFOLK,E07000245,3666,8157,176,365,1683,15,3233,540,176,667,18678,14047,4631,12364,Aged 16 to 24 years,2011

In [105]:
###THIS CELL WAS ADDED TO MAKE THE COLUMN NAMES MATCH UP BETWEEN THE TWO YEARS DATA AND THE FIXED COLLECTION DATA
###THIS RECTIFIED AN EARLIER MISTAKE IN RENAMING THE COLUMNS
combined_2011_df.rename(columns={'laua_code': 'laua'}, 
                                        inplace=True)
combined_2021_df.rename(columns={'2022 local authorities: district': 'laua_name', 'laua_code': 'laua'}, 
                                        inplace=True)
print(combined_2011_df[:2])
print(combined_2021_df[:2])

       laua_name       laua  \
0     DARLINGTON  E06000005
1  COUNTY DURHAM  E06000047

   Economically active: In employment: Employee: Part-time (including full-time students)  \
0                                                550
1                                               2239

   Economically active: In employment: Employee: Full-time (including full-time students)  \
0                                                343
1                                               1731

   Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0                                                200
1                                                828

   Economically active: In employment: Self-employed: Full-time (including full-time students)  \
0                                                213
1                                               1081

   Economically active: Unemployed (including full-time students)  \
0                                                 36
1                                                105

   Economically inactive: Retired  \
0                           16612
1                           82939

   Economically inactive: Student (including full-time students)  \
0                                                 19
1                                                129

   Economically inactive: Looking after home or family  \
0                                                 44
1                                                212

   Economically inactive: Long-term sick or disabled  \
0                                                192
1                                               1517

   Economically inactive: Other  Total Residents  Total Active  \
0                           230            18439          1342
1                          1564            92345          5984

   Total Inactive  Total Employed               Age Group  Year
0           17097            1306  Aged 65 years and over  2011
1           86361            5879  Aged 65 years and over  2011
       laua_name       laua  \
0     HARTLEPOOL  E06000001
1  MIDDLESBROUGH  E06000002

   Economically active (excluding full-time students): In employment  \
0                                               1339
1                                               1933

   Economically active (excluding full-time students): Unemployed  \
0                                                 51
1                                                 87

   Economically active and a full-time student: In employment  \
0                                                  1
1                                                  2

   Economically active and a full-time student: Unemployed  \
0                                                  0
1                                                  0

   Economically inactive (excluding full-time students)  \
0                                              16820
1                                              22131

   Economically inactive and a full-time student               Age Group  \
0                                             22  Aged 65 years and over
1                                             25  Aged 65 years and over

   Total Residents  Total Active  Total Inactive  Total Employed  Year
0            18233          1391           16842            1340  2021
1            24178          2022           22156            1935  2021

In [106]:
combined_2011_df

,laua_name,laua,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed,Age Group,Year
0,DARLINGTON,E06000005,550,343,200,213,36,16612,19,44,192,230,18439,1342,17097,1306,Aged 65 years and over,2011
1,COUNTY DURHAM,E06000047,2239,1731,828,1081,105,82939,129,212,1517,1564,92345,5984,86361,5879,Aged 65 years and over,2011
2,HARTLEPOOL,E06000001,336,291,90,102,25,14071,33,22,290,338,15598,844,14754,819,Aged 65 years and over,2011
3,MIDDLESBROUGH,E06000002,550,377,137,125,47,18446,42,56,456,455,20691,1236,19455,1189,Aged 65 years and over,2011
4,NORTHUMBERLAND,E06000057,1929,1250,1004,1181,95,56092,76,195,646,836,63304,5459,57845,5364,Aged 65 years and over,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,EAST SUFFOLK,E07000244,5307,7151,222,455,2735,13,4879,679,275,669,22385,15870,6515,13135,Aged 16 to 24 years,2011
0,NORTH NORTHAMPTONSHIRE,E06000061,6734,11394,213,627,3900,18,7091,1094,411,815,32297,22868,9429,18968,Aged 16 to 24 years,2011
0,SOMERSET WEST AND TAUNTON,E07000246,3513,5296,134,343,1335,10,3454,409,190,361,15045,10621,4424,9286,Aged 16 to 24 years,2011
0,WEST NORTHAMPTONSHIRE,E06000062,8859,13928,322,836,4538,20,10181,1047,429,1102,41262,28483,12779,23945,Aged 16 to 24 years,2011
0,WEST SUFFOLK,E07000245,3666,8157,176,365,1683,15,3233,540,176,667,18678,14047,4631,12364,Aged 16 to 24 years,2011

In [107]:
#check for null values
combined_2011_df.isna().sum()

laua_name                                                                                      0
laua                                                                                           0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-term sick or disabled                                              0
Economically inactive: Other                                                                   0
Total Residents                                                                                0
Total Active                                                                                   0
Total Inactive                                                                                 0
Total Employed                                                                                 0
Age Group                                                                                      0
Year                                                                                           0
dtype: int64

**I'm happy with the results above I believe the data has been suitably cleaned and is now ready to import into MongoDb.**

**EDIT** 

Having moved on from this notebook I realised that it might be worth while to estimate the part time to full time ratio of the 2021 data as this only categorises people 'In Employment' and doesn't draw the distinction.  I'm going to do this between here and the next bold markdown cell to show this was done later**

In [108]:
#cols

In [109]:
#combined_2011_df['F/T to P/T ratio'] = (combined_2011_df[cols[3]] + combined_2011_df[cols[5]])/(combined_2011_df[cols[2]]+ combined_2011_df[cols[4]])

In [110]:
#combined_2011_df

**the code lines above worked as expected however I have commented them out as they were messing with the code already written in the next notebook.  I kept them in here though in case I needed this later. End of update**

In [111]:
# Drop the fixed_broadband_collection collection
mongo_db.drop_collection('census_employment_collection')

{'ok': 0.0,
 'errmsg': 'ns not found',
 'code': 26,
 'codeName': 'NamespaceNotFound'}

In [112]:
census_collection = mongo_db["census_employment_collection"]

In [113]:
census_collection.insert_many(combined_2011_df.to_dict(orient='records'))

In [114]:
census_collection.insert_many(combined_2021_df.to_dict(orient='records'))

In [115]:
census_collection.count_documents({})

3641

##old experiment, kept to remember code but otherwise irrelevent.  All cells have been changed to markdown below here

for a, df in test_dfs_2011_agecombined.items():
    print(a)
    census_collection.insert_many(df.to_dict(orient='records'))

census_collection.count_documents({})

1655/5

for a, df in test_dfs['df_nomis_2023_08_06_172146.xlsx'].items():
    print(a)
    census_collection.insert_many(df.to_dict(orient='records'))

census_collection.count_documents({})

3641/11

#####



test_df1= test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 16 to 19']
new_cols = test_df1.loc[0].tolist()
old_cols = test_df1.columns
new_cols[1] = 'laua_code'

for i in range(len(old_cols)):
    test_df1.rename(columns= {old_cols[i]: new_cols[i]}, inplace =True)

test_df1

new_2011_dfs = {}
##old experiment, kept to remember code but otherwise irrelevent
for j in test_dfs['df_nomis_2023_08_06_174635.xlsx'].keys():
    df = test_dfs['df_nomis_2023_08_06_174635.xlsx'][j]
    for k in range(len(old_cols)):
        df.rename(columns= {old_cols[k]: new_cols[k]}, inplace =True)
    print('balls')   
    df[new_cols[2:]] = df[new_cols[2:]].astype(int)
    totals = []
    active_totals = []
    inactive_totals = []
    employed = []
    for index, row in df.iterrows():
        totals.append(row[new_cols[2:]].sum())
        employed.append(row[new_cols[2:6]].sum())
        active_totals.append(row[new_cols[2:7]].sum())
        inactive_totals.append(row[new_cols[7:]].sum())
    df['Active'] = active_totals
    df['Inactive'] = inactive_totals
    df['Total Employed'] = employed
    df['Population'] = totals
    new_2011_dfs[j] = df

new_2011_dfs['Age 16 to 19'].head()

The cell above shows there is an issue with the third age group as the print statement only executes twice. I'll investigate further

test_df2 = test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 22 to 24']
test_df2#[new_cols[2:]] = test_df2[new_cols[2:]].astype(int)

Right i can see theres a metadata row still included here which is clearly causing the problem.  I need to investigate why this is happening and why it hasn't happened with the first two

for i in test_dfs['df_nomis_2023_08_06_174635.xlsx'].keys():
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Unnamed: 0','Unnamed: 1'][:3])
    print()

test_df1.drop([0], inplace=True)
test_df1

test_df1.describe()


test_df1.dtypes

##get the data types right for adding values
test_df1[new_cols[2:]] = test_df1[new_cols[2:]].astype(int)
test_df1.dtypes

#okay no nulls great
test_df1.isna().sum()

new_cols[2:]

#calculate totals and add columns with these values
totals = []
active_totals = []
inactive_totals = []
employed = []
for index, row in test_df1.iterrows():
    totals.append(row[new_cols[2:]].sum())
    employed.append(row[new_cols[2:6]].sum())
    active_totals.append(row[new_cols[2:7]].sum())
    inactive_totals.append(row[new_cols[7:]].sum())
test_df1['Active'] = active_totals
test_df1['Inactive'] = inactive_totals
test_df1['Total Employed'] = employed
test_df1['Population'] = totals
test_df1

test_df1.dtypes

####check if there are any values > 0 in the 15 and under data
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 15 years and under'].sum()